package com.ssm.llp.base.common.model;

// Generated Jan 21, 2013 1:07:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.apache.wicket.markup.html.form.upload.FileUpload;

import com.ssm.llp.base.common.Parameter;

/**
 * LlpFileUpload generated by hbm2java
 */
@Entity
@Table(name = "rob_file_upload",uniqueConstraints = @UniqueConstraint(columnNames = "file_code"))
public class LlpFileUpload implements java.io.Serializable {

	private long fileUploadId;
	private String fileCode;
	private String fileType;
	private String fileName;
	private String fileDesc;
	private byte[] fileData;
	private String fileStatus = Parameter.FILE_STATUS_active;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private List<FileUpload> fileUploadTmp;

	public LlpFileUpload() {
	}

	public LlpFileUpload(long fileUploadId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.fileUploadId = fileUploadId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpFileUpload(long fileUploadId, String fileCode, String fileType, String fileName, String fileDesc, byte[] fileData, String fileStatus,
			Date createDt, String createBy, Date updateDt, String updateBy) {
		this.fileUploadId = fileUploadId;
		this.fileCode = fileCode;
		this.fileType = fileType;
		this.fileName = fileName;
		this.fileDesc = fileDesc;
		this.fileData = fileData;
		this.fileStatus = fileStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "file_upload_id", unique = true, nullable = false)
	public long getFileUploadId() {
		return this.fileUploadId;
	}

	public void setFileUploadId(long fileUploadId) {
		this.fileUploadId = fileUploadId;
	}

	@Column(name = "file_code", length = 50, unique=true)
	public String getFileCode() {
		return this.fileCode;
	}

	public void setFileCode(String fileCode) {
		this.fileCode = fileCode;
	}

	@Column(name = "file_type", length = 25)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_desc")
	public String getFileDesc() {
		return this.fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}

	@Lob
	@Column(name = "file_data")
	public byte[] getFileData() {
		return this.fileData;
	}

	public void setFileData(byte[] fileData) {
		this.fileData = fileData;
	}

	@Column(name = "file_status", length = 5)
	public String getFileStatus() {
		return this.fileStatus;
	}

	public void setFileStatus(String fileStatus) {
		this.fileStatus = fileStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Transient
	public List<FileUpload> getFileUploadTmp() {
		return fileUploadTmp;
	}

	public void setFileUploadTmp(List<FileUpload> fileUploadTmp) {
		this.fileUploadTmp = fileUploadTmp;
	}


}
