package com.ssm.llp.base.common.model;

// Generated Jan 3, 2013 9:36:37 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;
import org.hibernate.envers.Audited;

/**
 * LlpLocaleMessage generated by hbm2java
 */
@Entity
@Table(name = "rob_locale_message")
@Audited
public class LlpLocaleMessage implements java.io.Serializable {

	private long localeMessageId;
	private String key;
	private String locale;
	private String msg;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public LlpLocaleMessage() {
	}

	public LlpLocaleMessage(long localeMessageId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.localeMessageId = localeMessageId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpLocaleMessage(long localeMessageId, String key, String locale, String msg, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.localeMessageId = localeMessageId;
		this.key = key;
		this.locale = locale;
		this.msg = msg;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "locale_message_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getLocaleMessageId() {
		return this.localeMessageId;
	}

	public void setLocaleMessageId(long localeMessageId) {
		this.localeMessageId = localeMessageId;
	}

	@Column(name = "key", length = 150)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "locale", length = 10)
	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	@Column(name = "msg")
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Transient
	public String getKeyLocale(){
		String keyLocale = getKey();
		if(StringUtils.isNotBlank(getLocale())){
			return getKey()+":"+getLocale();
		}
		return getKey()+":";
	}
}
