package com.ssm.llp.base.common.model;

// Generated Dec 6, 2012 1:29:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

/**
 * LlpPaymentTransactionDetail generated by hbm2java
 */
@Entity
@Table(name = "rob_payment_transaction_detail")
@Audited
public class LlpPaymentTransactionDetail implements java.io.Serializable {

	private long transactionDetailId;
//	private LlpPaymentTransaction llpPaymentTransaction;
	private String transactionId;
	private String paymentItem;
	private int quantity;
	private double amount;
	private String paymentDet;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private double gstAmt;
	private double amountWithOutGst;
	private String gstCode;

	public LlpPaymentTransactionDetail() {
	}

	public LlpPaymentTransactionDetail(long transactionDetailId,
//			LlpPaymentTransaction llpPaymentTransaction, 
			String transactionId,
			String paymentItem,
			int quantity, double amount, Date createDt, String createBy,
			Date updateDt, String updateBy) {
		this.transactionDetailId = transactionDetailId;
//		this.llpPaymentTransaction = llpPaymentTransaction;
		this.transactionId = transactionId;
		this.paymentItem = paymentItem;
		this.quantity = quantity;
		this.amount = amount;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "transaction_detail_id", unique = true, nullable = false)
	public long getTransactionDetailId() {
		return this.transactionDetailId;
	}

	public void setTransactionDetailId(long transactionDetailId) {
		this.transactionDetailId = transactionDetailId;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "transaction_id", nullable = false)
//	public LlpPaymentTransaction getLlpPaymentTransaction() {
//		return this.llpPaymentTransaction;
//	}

//	public void setLlpPaymentTransaction(
//			LlpPaymentTransaction llpPaymentTransaction) {
//		this.llpPaymentTransaction = llpPaymentTransaction;
//	}
	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "transaction_id", nullable = false)
	@Column(name = "transaction_id", nullable = false, length = 50)
	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "payment_item", nullable = false, length = 20)
	public String getPaymentItem() {
		return this.paymentItem;
	}

	public void setPaymentItem(String paymentItem) {
		this.paymentItem = paymentItem;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "amount", nullable = false, precision = 16, scale=2)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "payment_det", length = 255)
	public String getPaymentDet() {
		return paymentDet;
	}

	public void setPaymentDet(String paymentDet) {
		this.paymentDet = paymentDet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "gst_amt", precision = 16, scale=2)
	public double getGstAmt() {
		return gstAmt;
	}

	public void setGstAmt(double gstAmt) {
		this.gstAmt = gstAmt;
	}

	@Transient
	public double getAmountWithOutGst() {
		return getAmount()-getGstAmt();
	}

	public void setAmountWithOutGst(double amountWithOutGst) {
		this.amountWithOutGst = amountWithOutGst;
	}

	@Column(name = "gst_code", length = 5)
	public String getGstCode() {
		return gstCode;
	}

	public void setGstCode(String gstCode) {
		this.gstCode = gstCode;
	}
}
