package com.ssm.llp.base.common.model;

// Generated Feb 27, 2013 5:42:15 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ssm.llp.mod1.model.LlpRegistration;

/**
 * LlpRegTransaction generated by hbm2java
 */
@Entity
@Table(name = "rob_reg_transaction")
public class LlpRegTransaction implements java.io.Serializable {

	private long regTransactionId;
	private String nsRefNo;
	private byte[] regData;
	private String paymentTransactionId;
	private String status;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private LlpRegistration llpRegistration;
	
	
	public LlpRegTransaction() {
	}

	public LlpRegTransaction(long regTransactionId, String nsRefNo, String paymentTransactionId, String status, Date createDt, String createBy,
			Date updateDt, String updateBy) {
		this.regTransactionId = regTransactionId;
		this.nsRefNo = nsRefNo;
		this.paymentTransactionId = paymentTransactionId;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpRegTransaction(long regTransactionId, String nsRefNo, byte[] regData, String paymentTransactionId, String status, Date createDt,
			String createBy, Date updateDt, String updateBy) {
		this.regTransactionId = regTransactionId;
		this.nsRefNo = nsRefNo;
		this.regData = regData;
		this.paymentTransactionId = paymentTransactionId;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "reg_transaction_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRegTransactionId() {
		return this.regTransactionId;
	}

	public void setRegTransactionId(long regTransactionId) {
		this.regTransactionId = regTransactionId;
	}

	@Column(name = "ns_ref_no", nullable = false, length = 30)
	public String getNsRefNo() {
		return this.nsRefNo;
	}

	public void setNsRefNo(String nsRefNo) {
		this.nsRefNo = nsRefNo;
	}

	@Column(name = "reg_data")
	public byte[] getRegData() {
		return this.regData;
	}

	public void setRegData(byte[] regData) {
		this.regData = regData;
	}

	@Column(name = "payment_transaction_id",  length = 50)
	public String getPaymentTransactionId() {
		return this.paymentTransactionId;
	}

	public void setPaymentTransactionId(String paymentTransactionId) {
		this.paymentTransactionId = paymentTransactionId;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Transient
	public LlpRegistration getLlpRegistration() {
		return llpRegistration;
	}

	public void setLlpRegistration(LlpRegistration llpRegistration) {
		this.llpRegistration = llpRegistration;
	}

}
