package com.ssm.llp.base.common.model;

// Generated May 17, 2013 9:58:34 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.ssm.llp.base.common.Parameter;

/**
 * LlpSupplyInfoDtl generated by hbm2java
 */
@Entity
@Table(name = "rob_supply_info_dtl")
public class LlpSupplyInfoDtl implements java.io.Serializable {

	private long dtlId;
	private String hdrCode;
	private String entityType;
	private String entityNo;
	private String entityName;
	
	private String profileStatus = Parameter.SUPPLY_INFO_DTL_ATTACHMENT_STATUS_not_selected;
	private String certStatus = Parameter.SUPPLY_INFO_DTL_ATTACHMENT_STATUS_not_selected;;
	private byte[] profileData;
	private byte[] certData;
	
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	
	private boolean isProfileSelected=false;
	private boolean isCertSelected=false;

	public LlpSupplyInfoDtl() {
	}

	public LlpSupplyInfoDtl(long dtlId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.dtlId = dtlId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpSupplyInfoDtl(long dtlId, String hdrCode, String infoType, String fileName, byte[] fileData, String dtlStatus, Date createDt,
			String createBy, Date updateDt, String updateBy) {
		this.dtlId = dtlId;
		this.hdrCode = hdrCode;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "dtl_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getDtlId() {
		return this.dtlId;
	}

	public void setDtlId(long dtlId) {
		this.dtlId = dtlId;
	}

	@Column(name = "hdr_code", length = 50)
	public String getHdrCode() {
		return this.hdrCode;
	}

	public void setHdrCode(String hdrCode) {
		this.hdrCode = hdrCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	
	@Column(name = "entity_no", length = 25)
	public String getEntityNo() {
		return this.entityNo;
	}

	public void setEntityNo(String entityNo) {
		this.entityNo = entityNo;
	}

	@Column(name = "entity_name")
	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "profile_status", length = 5)
	public String getProfileStatus() {
		return profileStatus;
	}

	public void setProfileStatus(String profileStatus) {
		this.profileStatus = profileStatus;
	}

	@Column(name = "cert_status", length = 5)
	public String getCertStatus() {
		return certStatus;
	}

	public void setCertStatus(String certStatus) {
		this.certStatus = certStatus;
	}

	@Column(name = "profile_data")
	public byte[] getProfileData() {
		return profileData;
	}

	public void setProfileData(byte[] profileData) {
		this.profileData = profileData;
	}

	@Column(name = "cert_data")
	public byte[] getCertData() {
		return certData;
	}

	public void setCertData(byte[] certData) {
		this.certData = certData;
	}
	
	
	@Column(name = "is_profile_selected")
	public boolean getIsProfileSelected() {
		return this.isProfileSelected;
	}

	public void setIsProfileSelected(boolean isProfileSelected) {
		this.isProfileSelected = isProfileSelected;
	}

	@Column(name = "is_cert_selected")
	public boolean getIsCertSelected() {
		return this.isCertSelected;
	}

	public void setIsCertSelected(boolean isCertSelected) {
		this.isCertSelected = isCertSelected;
	}

	@Column(name = "entity_type")
	public String getEntityType() {
		return entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

}
