package com.ssm.llp.base.common.model;

// Generated Dec 17, 2012 8:34:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LlpUserLog generated by hbm2java
 */
@Entity
@Table(name = "rob_user_log")
public class LlpUserLog implements java.io.Serializable {

	private long userLogId;
	private String loginId;
	private Date loginTime;
	private Date logoutTime;
	private String createBy;
	private Date createDt;
	private String ipAddress;
	private String loginType;
	private String loginSource;
	private String reqUrl;

	public LlpUserLog() {
	}

	public LlpUserLog(long userLogId, Date loginTime, Date createDt) {
		this.userLogId = userLogId;
		this.loginTime = loginTime;
		this.createDt = createDt;
	}

	public LlpUserLog(long userLogId, String loginId, Date loginTime, Date logoutTime, String createBy, Date createDt, String ipAddress) {
		this.userLogId = userLogId;
		this.loginId = loginId;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.createBy = createBy;
		this.createDt = createDt;
		this.ipAddress = ipAddress;
	}

	@Id
	@Column(name = "user_log_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getUserLogId() {
		return this.userLogId;
	}

	public void setUserLogId(long userLogId) {
		this.userLogId = userLogId;
	}

	@Column(name = "login_id", length = 50)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", nullable = false, length = 3594)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 3594)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "create_by", length = 10)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "ip_address", length = 50)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "login_type", length = 30)
	public String getLoginType() {
		return loginType;
	}

	public void setLoginType(String loginType) {
		this.loginType = loginType;
	}

	@Column(name = "login_source", length = 30)
	public String getLoginSource() {
		return loginSource;
	}

	public void setLoginSource(String loginSource) {
		this.loginSource = loginSource;
	}

	@Column(name = "req_url", length = 30)
	public String getReqUrl() {
		return reqUrl;
	}

	public void setReqUrl(String reqUrl) {
		this.reqUrl = reqUrl;
	}

}
