package com.ssm.llp.ezbiz.model;

// Generated Jan 14, 2016 11:44:02 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import com.ssm.llp.base.common.Parameter;
import com.ssm.llp.base.common.model.LlpFileData;

/**
 * RobFormAOwner generated by hbm2java
 */
@Entity
@Table(name = "rob_form_b4")
public class RobFormB4 implements java.io.Serializable {

	private long robFormB4Id;
	private Long cbsOwnerId;
	private String robFormBCode;
	private String name;
	private Date dob;
	private String nationality;
	private String countryoforiginifpr;
	private String oldicno;
	private String newicno;
	private String iccolor;
	private String gender;
	private String race;
	private String otherrace;
	private String telNo;
	private String mobileNo;
	private String email;
	private String ownershiptype;
//	private String alreadygetpartnerconcent;
	private String addr;
	private String addr2;
	private String addr3;
	private String addrTown;
	private String addrPostcode;
	private String addrState;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private String ezbizLoginName;
	private String ezbizUserRefNo;
	private String ammendmentType;
	private Date ammendmentDate;
	
	private LlpFileData supportingDocData;
	
	public RobFormB4() {
	}

	public RobFormB4(long robFormB4Id, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormB4Id = robFormB4Id;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobFormB4(long robFormB4Id, String robFormBCode, String name, Date dob, String nationality, String countryoforiginifpr,
			String oldicno, String newicno, String iccolor, String gender, String race, String otherrace, String telno,
			String email, String ownershiptype, String addr, String addrTown, String addrPostcode,
			String addrState, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormB4Id = robFormB4Id;
		this.robFormBCode = robFormBCode;
		this.name = name;
		this.dob = dob;
		this.nationality = nationality;
		this.countryoforiginifpr = countryoforiginifpr;
		this.oldicno = oldicno;
		this.newicno = newicno;
		this.iccolor = iccolor;
		this.gender = gender;
		this.race = race;
		this.otherrace = otherrace;
		this.telNo = telno;
		this.email = email;
		this.ownershiptype = ownershiptype;
		this.addr = addr;
		this.addrTown = addrTown;
		this.addrPostcode = addrPostcode;
		this.addrState = addrState;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_form_b4_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormB4Id() {
		return this.robFormB4Id;
	}

	public void setRobFormB4Id(long robFormB4Id) {
		this.robFormB4Id = robFormB4Id;
	}

	@Column(name = "rob_form_B_code", length = 25)
	public String getRobFormBCode() {
		return this.robFormBCode;
	}

	public void setRobFormBCode(String robFormBCode) {
		this.robFormBCode = robFormBCode;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 2052)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "nationality", length = 3)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "countryoforiginifpr", length = 3)
	public String getCountryoforiginifpr() {
		return this.countryoforiginifpr;
	}

	public void setCountryoforiginifpr(String countryoforiginifpr) {
		this.countryoforiginifpr = countryoforiginifpr;
	}

	@Column(name = "oldicno", length = 15)
	public String getOldicno() {
		return this.oldicno;
	}

	public void setOldicno(String oldicno) {
		this.oldicno = oldicno;
	}

	@Column(name = "newicno", length = 12)
	public String getNewicno() {
		return this.newicno;
	}

	public void setNewicno(String newicno) {
		this.newicno = newicno;
	}

	@Column(name = "iccolor", length = 1)
	public String getIccolor() {
		return this.iccolor;
	}

	public void setIccolor(String iccolor) {
		this.iccolor = iccolor;
	}

	@Column(name = "gender", length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "race", length = 1)
	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	@Column(name = "otherrace")
	public String getOtherrace() {
		return this.otherrace;
	}

	public void setOtherrace(String otherrace) {
		this.otherrace = otherrace;
	}

	@Column(name = "tel_no", length = 11)
	public String getTelNo() {
		return this.telNo;
	}

	public void setTelNo(String telNo) {
		this.telNo = telNo;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ownershiptype", length = 1)
	public String getOwnershiptype() {
		return this.ownershiptype;
	}

	public void setOwnershiptype(String ownershiptype) {
		this.ownershiptype = ownershiptype;
	}

//	@Column(name = "alreadygetpartnerconcent", length = 1)
//	public String getAlreadygetpartnerconcent() {
//		return this.alreadygetpartnerconcent;
//	}
//
//	public void setAlreadygetpartnerconcent(String alreadygetpartnerconcent) {
//		this.alreadygetpartnerconcent = alreadygetpartnerconcent;
//	}

	@Column(name = "addr", length = 70)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "addr_town", length = 20)
	public String getAddrTown() {
		return this.addrTown;
	}

	public void setAddrTown(String addrTown) {
		this.addrTown = addrTown;
	}

	@Column(name = "addr_postcode", length = 5)
	public String getAddrPostcode() {
		return this.addrPostcode;
	}

	public void setAddrPostcode(String addrPostcode) {
		this.addrPostcode = addrPostcode;
	}

	@Column(name = "addr_state", length = 2)
	public String getAddrState() {
		return this.addrState;
	}

	public void setAddrState(String addrState) {
		this.addrState = addrState;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "mobile_no", length = 11)
	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "ezbiz_login_name", length = 50)
	public String getEzbizLoginName() {
		return ezbizLoginName;
	}

	public void setEzbizLoginName(String ezbizLoginName) {
		this.ezbizLoginName = ezbizLoginName;
	}

	@Column(name = "addr2", length = 70)
	public String getAddr2() {
		return addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "addr3", length = 70)
	public String getAddr3() {
		return addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	@Column(name = "ammendment_type")
	public String getAmmendmentType() {
		return ammendmentType;
	}

	public void setAmmendmentType(String ammendmentType) {
		this.ammendmentType = ammendmentType;
	}

	@Column(name = "cbs_owner_id")
	public Long getCbsOwnerId() {
		return cbsOwnerId;
	}

	public void setCbsOwnerId(Long cbsOwnerId) {
		this.cbsOwnerId = cbsOwnerId;
	}


	@Column(name = "ezbiz_user_ref_no", length = 50)
	public String getEzbizUserRefNo() {
		return ezbizUserRefNo;
	}

	public void setEzbizUserRefNo(String ezbizUserRefNo) {
		this.ezbizUserRefNo = ezbizUserRefNo;
	}

	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ammendment_date", length = 2052)
	public Date getAmmendmentDate() {
		return ammendmentDate;
	}

	public void setAmmendmentDate(Date ammendmentDate) {
		this.ammendmentDate = ammendmentDate;
	}
	
	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="supporting_doc_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public LlpFileData getSupportingDocData() {
		return supportingDocData;
	}

	public void setSupportingDocData(LlpFileData supportingDocData) {
		this.supportingDocData = supportingDocData;
	}

}
