package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 4:52:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * CmpDetail generated by hbm2java
 */
@Entity
@Audited
@Table(name = "cmp_detail")
public class CmpDetail implements java.io.Serializable {

	private long cmpDetailId;
	private Long cmpMasterId;
	private String cmpSectionCode;
	private String cmpSectionDesc;
	private String cmpSectionOffence;
	private double cmpSectionAmt;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public CmpDetail() {
	}

	public CmpDetail(long cmpDetailId, String cmpSectionCode, String cmpSectionDesc, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.cmpDetailId = cmpDetailId;
		this.cmpSectionCode = cmpSectionCode;
		this.cmpSectionDesc = cmpSectionDesc;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public CmpDetail(long cmpDetailId, Long cmpMasterId, String cmpSectionCode, String cmpSectionDesc, String cmpSectionOffence,
			double cmpSectionAmt, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.cmpDetailId = cmpDetailId;
		this.cmpMasterId = cmpMasterId;
		this.cmpSectionCode = cmpSectionCode;
		this.cmpSectionDesc = cmpSectionDesc;
		this.cmpSectionOffence = cmpSectionOffence;
		this.cmpSectionAmt = cmpSectionAmt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy; wekk wekkk
	}

	@Id
	@Column(name = "cmp_detail_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getCmpDetailId() {
		return this.cmpDetailId;
	}

	public void setCmpDetailId(long cmpDetailId) {
		this.cmpDetailId = cmpDetailId;
	}

	@Column(name = "cmp_master_id")
	public Long getCmpMasterId() {
		return this.cmpMasterId;
	}

	public void setCmpMasterId(Long cmpMasterId) {
		this.cmpMasterId = cmpMasterId;
	}

	@Column(name = "cmp_section_code", length = 30)
	public String getCmpSectionCode() {
		return this.cmpSectionCode;
	}

	public void setCmpSectionCode(String cmpSectionCode) {
		this.cmpSectionCode = cmpSectionCode;
	}

	@Column(name = "cmp_section_desc")
	public String getCmpSectionDesc() {
		return this.cmpSectionDesc;
	}

	public void setCmpSectionDesc(String cmpSectionDesc) {
		this.cmpSectionDesc = cmpSectionDesc;
	}

	@Column(name = "cmp_section_offence", length = 2000)
	public String getCmpSectionOffence() {
		return this.cmpSectionOffence;
	}

	public void setCmpSectionOffence(String cmpSectionOffence) {
		this.cmpSectionOffence = cmpSectionOffence;
	}

	@Column(name = "cmp_section_amt", precision = 16)
	public double getCmpSectionAmt() {
		return this.cmpSectionAmt;
	}

	public void setCmpSectionAmt(double cmpSectionAmt) {
		this.cmpSectionAmt = cmpSectionAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
