package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 4:52:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * CmpMaster generated by hbm2java
 */
@Entity
@Audited
@Table(name = "cmp_master")
public class CmpMaster implements java.io.Serializable {

	private long cmpMasterId;
	private Long cmpMasterKeyCode;
	private String cmpTransactionCode;
	private Date ammendmendDt;
	private String cmpNo;
	private String cmpStatus;
	private String entityType;
	private String entityNo;
	private String entityNoCheckDigit;
	private double cmpAmt;
	private String entityName;
	private String cmpType;
	private String entity_name_reg;
	
	
	@Column(name = "entity_name_reg", length = 200)
	public String getEntity_name_reg() {
		return entity_name_reg;
	}

	public void setEntity_name_reg(String entity_name_reg) {
		this.entity_name_reg = entity_name_reg;
	}

	@Column(name = "entity_name", length = 100)
	public String getEntityName() {
		return entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	@Column(name = "cmp_type", length = 50)
	public String getCmpType() {
		return cmpType;
	}

	public void setCmpType(String cmpType) {
		this.cmpType = cmpType;
	}

	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public CmpMaster() {
	}

	public CmpMaster(long cmpMasterId, String cmpTransactionCode, Date ammendmendDt, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.cmpMasterId = cmpMasterId;
		this.cmpTransactionCode = cmpTransactionCode;
		this.ammendmendDt = ammendmendDt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public CmpMaster(long cmpMasterId, String cmpTransactionCode, Date ammendmendDt, String cmpNo, String cmpStatus, String entityType,
			String entityNo, String entityNoCheckDigit, double cmpAmt, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.cmpMasterId = cmpMasterId;
		this.cmpTransactionCode = cmpTransactionCode;
		this.ammendmendDt = ammendmendDt;
		this.cmpNo = cmpNo;
		this.cmpStatus = cmpStatus;
		this.entityType = entityType;
		this.entityNo = entityNo;
		this.entityNoCheckDigit = entityNoCheckDigit;
		this.cmpAmt = cmpAmt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "cmp_master_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getCmpMasterId() {
		return this.cmpMasterId;
	}

	public void setCmpMasterId(long cmpMasterId) {
		this.cmpMasterId = cmpMasterId;
	}

	@Column(name = "cmp_transaction_code", nullable = false, length = 25)
	public String getCmpTransactionCode() {
		return this.cmpTransactionCode;
	}

	public void setCmpTransactionCode(String cmpTransactionCode) {
		this.cmpTransactionCode = cmpTransactionCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ammendmend_dt", length = 2052)
	public Date getAmmendmendDt() {
		return this.ammendmendDt;
	}

	public void setAmmendmendDt(Date ammendmendDt) {
		this.ammendmendDt = ammendmendDt;
	}

	@Column(name = "cmp_no", length = 50)
	public String getCmpNo() {
		return this.cmpNo;
	}

	public void setCmpNo(String cmpNo) {
		this.cmpNo = cmpNo;
	}

	@Column(name = "cmp_status", length = 10)
	public String getCmpStatus() {
		return this.cmpStatus;
	}

	public void setCmpStatus(String cmpStatus) {
		this.cmpStatus = cmpStatus;
	}

	@Column(name = "entity_type", length = 10)
	public String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	@Column(name = "entity_no", length = 20)
	public String getEntityNo() {
		return this.entityNo;
	}

	public void setEntityNo(String entityNo) {
		this.entityNo = entityNo;
	}

	@Column(name = "entity_no_check_digit", length = 2)
	public String getEntityNoCheckDigit() {
		return this.entityNoCheckDigit;
	}

	public void setEntityNoCheckDigit(String entityNoCheckDigit) {
		this.entityNoCheckDigit = entityNoCheckDigit;
	}

	@Column(name = "cmp_amt", precision = 16)
	public double getCmpAmt() {
		return this.cmpAmt;
	}

	public void setCmpAmt(double cmpAmt) {
		this.cmpAmt = cmpAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "cmp_master_key_code")
	public Long getCmpMasterKeyCode() {
		return cmpMasterKeyCode;
	}

	public void setCmpMasterKeyCode(Long cmpMasterKeyCode) {
		this.cmpMasterKeyCode = cmpMasterKeyCode;
	}

}
