package com.ssm.llp.ezbiz.model;

// Generated Jul 27, 2016 3:44:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * RobEBranchTransactionDetail generated by hbm2java
 */
@Entity
@Table(name = "rob_ebranch_transaction_detail")
@Audited
public class RobEBranchTransactionDetail implements java.io.Serializable {

	private long robEBranchTransactionDetailId;
	private Long robEBranchTransactionId;
	private Long robEbranchId;
	private String platform;
	private String platformOthers;
	private String url;
	private String actionStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public RobEBranchTransactionDetail() {
	}

	public RobEBranchTransactionDetail(long robEBranchTransactionDetailId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robEBranchTransactionDetailId = robEBranchTransactionDetailId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobEBranchTransactionDetail(long robEBranchTransactionDetailId, Long robEBranchTransactionId, Long robEbranchId, String platform, String platformOthers,
			String url, String actionStatus, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robEBranchTransactionDetailId = robEBranchTransactionDetailId;
		this.robEBranchTransactionId = robEBranchTransactionId;
		this.robEbranchId = robEbranchId;
		this.platform = platform;
		this.platformOthers = platformOthers;
		this.url = url;
		this.actionStatus = actionStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}
	
	@Id
	@Column(name = "rob_ebranch_transaction_detail_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobEBranchTransactionDetailId() {
		return robEBranchTransactionDetailId;
	}

	public void setRobEBranchTransactionDetailId(long robEBranchTransactionDetailId) {
		this.robEBranchTransactionDetailId = robEBranchTransactionDetailId;
	}

	@Column(name = "rob_ebranch_transaction_id")
	public Long getRobEBranchTransactionId() {
		return robEBranchTransactionId;
	}

	public void setRobEBranchTransactionId(Long robEBranchTransactionId) {
		this.robEBranchTransactionId = robEBranchTransactionId;
	}

	@Column(name = "rob_ebranch_id")
	public Long getRobEbranchId() {
		return this.robEbranchId;
	}

	public void setRobEbranchId(Long robEbranchId) {
		this.robEbranchId = robEbranchId;
	}

	@Column(name = "platform", length = 2)
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "platform_others", length = 200)
	public String getPlatformOthers() {
		return this.platformOthers;
	}

	public void setPlatformOthers(String platformOthers) {
		this.platformOthers = platformOthers;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "action_status", length = 2)
	public String getActionStatus() {
		return this.actionStatus;
	}

	public void setActionStatus(String actionStatus) {
		this.actionStatus = actionStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	
}
