package com.ssm.llp.ezbiz.model;

// Generated Jul 27, 2016 4:01:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * RobEbranch generated by hbm2java
 */
@Entity
@Table(name = "rob_ebranch")
@Audited
public class RobEBranch implements java.io.Serializable {

	private long robEbranchId;
	private String name;
	private String brNo;
	private String chkDigit;
	private String platform;
	private String platformOthers;
	private String url;
	private String status;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public RobEBranch() {
	}

	public RobEBranch(long robEbranchId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robEbranchId = robEbranchId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobEBranch(long robEbranchId, String name, String brNo, String chkDigit, String platform, String platformOthers, String url,
			String status, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robEbranchId = robEbranchId;
		this.name = name;
		this.brNo = brNo;
		this.chkDigit = chkDigit;
		this.platform = platform;
		this.platformOthers = platformOthers;
		this.url = url;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_ebranch_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobEbranchId() {
		return this.robEbranchId;
	}

	public void setRobEbranchId(long robEbranchId) {
		this.robEbranchId = robEbranchId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "br_no", length = 10)
	public String getBrNo() {
		return this.brNo;
	}

	public void setBrNo(String brNo) {
		this.brNo = brNo;
	}

	@Column(name = "chk_digit", length = 2)
	public String getChkDigit() {
		return this.chkDigit;
	}

	public void setChkDigit(String chkDigit) {
		this.chkDigit = chkDigit;
	}

	@Column(name = "platform", length = 2)
	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	@Column(name = "platform_others", length = 200)
	public String getPlatformOthers() {
		return this.platformOthers;
	}

	public void setPlatformOthers(String platformOthers) {
		this.platformOthers = platformOthers;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
