package com.ssm.llp.ezbiz.model;

// Generated Jan 14, 2016 11:44:02 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

/**
 * RobFormABizCode generated by hbm2java
 */
@Entity
@Table(name = "rob_form_notes")
@Audited
public class RobFormNotes implements java.io.Serializable {

	private long robFormNoteId;
	private String robFormCode;
	private String notes;
	private String notesAnswer;
	private Date createDt;
	private String createBy;
	private String robFormType;
	private String queryBy;
	private Date updateDt;
	private String updateBy;
	



	public RobFormNotes() {
	}

	public RobFormNotes(long robFormNoteId, Date createDt, String createBy) {
		this.robFormNoteId = robFormNoteId;
		this.createDt = createDt;
		this.createBy = createBy;
	}
	
	@Id
	@Column(name = "rob_form_notes_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormNoteId() {
		return robFormNoteId;
	}

	public void setRobFormNoteId(long robFormNoteId) {
		this.robFormNoteId = robFormNoteId;
	}

	@Column(name = "rob_form_code", length = 25)
	public String getRobFormCode() {
		return robFormCode;
	}

	public void setRobFormCode(String robFormCode) {
		this.robFormCode = robFormCode;
	}

	@Column(name = "rob_form_type", length = 25)
	public String getRobFormType() {
		return robFormType;
	}

	public void setRobFormType(String robFormType) {
		this.robFormType = robFormType;
	}
	
	@Column(name = "notes")
	public String getNotes() {
		return notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "notes_answer", length = 500)
	public String getNotesAnswer() {
		return notesAnswer;
	}

	public void setNotesAnswer(String notesAnswer) {
		this.notesAnswer = notesAnswer;
	}

	@Column(name = "query_by", length = 50)
	public String getQueryBy() {
		return queryBy;
	}

	public void setQueryBy(String queryBy) {
		this.queryBy = queryBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", length = 3594)
	public Date getUpdateDt() {
		return updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", length = 50)
	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
