package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 3:52:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

/**
 * RobFormB2Det generated by hbm2java
 */
@Entity
@Audited
@Table(name = "rob_form_b2_det")
public class RobFormB2Det implements java.io.Serializable {

	private long robFormB2DetId;
	private String robFormBCode;
	private String bizCode;
	private String bizCodeDesc;
	private String ammendmentType;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private Boolean selected = Boolean.FALSE;
	

	public RobFormB2Det() {
	}

	public RobFormB2Det(long robFormB2DetId, String robFormBCode, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormB2DetId = robFormB2DetId;
		this.robFormBCode = robFormBCode;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobFormB2Det(long robFormB2DetId, String robFormBCode, String bizCode, String bizCodeDesc, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.robFormB2DetId = robFormB2DetId;
		this.robFormBCode = robFormBCode;
		this.bizCode = bizCode;
		this.bizCodeDesc = bizCodeDesc;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}
	public RobFormB2Det(String code, String codeDesc) {
		bizCode = code;
		bizCodeDesc = codeDesc;
	}

	@Id
	@Column(name = "rob_form_b2_det_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormB2DetId() {
		return this.robFormB2DetId;
	}

	public void setRobFormB2DetId(long robFormB2DetId) {
		this.robFormB2DetId = robFormB2DetId;
	}

	@Column(name = "rob_form_b_code", nullable = false, length = 25)
	public String getRobFormBCode() {
		return this.robFormBCode;
	}

	public void setRobFormBCode(String robFormBCode) {
		this.robFormBCode = robFormBCode;
	}

	@Column(name = "biz_code", length = 70)
	public String getBizCode() {
		return this.bizCode;
	}

	public void setBizCode(String bizCode) {
		this.bizCode = bizCode;
	}

	@Column(name = "biz_code_desc", length = 200)
	public String getBizCodeDesc() {
		return this.bizCodeDesc;
	}

	public void setBizCodeDesc(String bizCodeDesc) {
		this.bizCodeDesc = bizCodeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Transient
	public Boolean getSelected() {
		return selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	@Column(name = "ammendment_type", nullable = false, length = 10)
	public String getAmmendmentType() {
		return ammendmentType;
	}

	public void setAmmendmentType(String ammendmentType) {
		this.ammendmentType = ammendmentType;
	}

}
