package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 5:17:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

import com.ssm.webis.param.RobFormOwnerInfo;

/**
 * RobFormOwnerVerification generated by hbm2java
 */
@Entity
@Audited
@Table(name = "rob_form_owner_verification")
public class RobFormOwnerVerification implements java.io.Serializable {

	private long robFormOwnerVerificationId;
	private String robFormCode;
	private String robFormType;
	private String userRefNo;
	private String idType;
	private String name;
	private String idNo;
	private String status;
	
	
	
	private String emailStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	
	private RobFormOwnerInfo cbsOwnerInfo;

	public RobFormOwnerVerification() {
	}

	public RobFormOwnerVerification(long robFormOwnerVerificationId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormOwnerVerificationId = robFormOwnerVerificationId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobFormOwnerVerification(long robFormOwnerVerificationId, String robFormCode, String userRefNo, String idType, String idNo, String status,
			Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormOwnerVerificationId = robFormOwnerVerificationId;
		this.robFormCode = robFormCode;
		this.userRefNo = userRefNo;
		this.idType = idType;
		this.idNo = idNo;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_form_owner_verification_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormOwnerVerificationId() {
		return this.robFormOwnerVerificationId;
	}

	public void setRobFormOwnerVerificationId(long robFormOwnerVerificationId) {
		this.robFormOwnerVerificationId = robFormOwnerVerificationId;
	}

	@Column(name = "rob_form_code", length = 25)
	public String getRobFormCode() {
		return this.robFormCode;
	}

	public void setRobFormCode(String robFormCode) {
		this.robFormCode = robFormCode;
	}

	@Column(name = "user_ref_no", length = 25)
	public String getUserRefNo() {
		return this.userRefNo;
	}

	public void setUserRefNo(String userRefNo) {
		this.userRefNo = userRefNo;
	}

	@Column(name = "id_type", length = 2)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "id_no", length = 20)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "form_type", length = 2)
	public String getRobFormType() {
		return robFormType;
	}

	public void setRobFormType(String robFormType) {
		this.robFormType = robFormType;
	}

	@Column(name = "email_status", length = 2)
	public String getEmailStatus() {
		return emailStatus;
	}

	public void setEmailStatus(String emailStatus) {
		this.emailStatus = emailStatus;
	}

	@Transient
	public RobFormOwnerInfo getCbsOwnerInfo() {
		return cbsOwnerInfo;
	}

	public void setCbsOwnerInfo(RobFormOwnerInfo cbsOwnerInfo) {
		this.cbsOwnerInfo = cbsOwnerInfo;
	}

}
