package com.ssm.llp.ezbiz.model;

// Generated Jan 14, 2016 11:44:02 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.StringUtils;
import org.hibernate.envers.Audited;

/**
 * RobFormABranches generated by hbm2java
 */
@Entity
@Table(name = "rob_form_a_branches")
@Audited
public class RobFormABranches implements java.io.Serializable {

	private long robFormABranchesId;
	private String robFormACode;
	private String addr;
	private String addr2;
	private String addr3;
	private String addrTown;
	private String addrPostcode;
	private String addrState;
	private String addrUrl;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public RobFormABranches() {
	}

	public RobFormABranches(long robFormABranchesId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormABranchesId = robFormABranchesId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobFormABranches(long robFormABranchesId, String robFormACode, String addr, String addrTown, String addrPostcode,
			String addrState, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormABranchesId = robFormABranchesId;
		this.robFormACode = robFormACode;
		this.addr = addr;
		this.addrTown = addrTown;
		this.addrPostcode = addrPostcode;
		this.addrState = addrState;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_form_a_branches_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormABranchesId() {
		return this.robFormABranchesId;
	}

	public void setRobFormABranchesId(long robFormABranchesId) {
		this.robFormABranchesId = robFormABranchesId;
	}

	@Column(name = "rob_form_a_code", length = 25)
	public String getRobFormACode() {
		return this.robFormACode;
	}

	public void setRobFormACode(String robFormACode) {
		this.robFormACode = robFormACode;
	}

	@Column(name = "addr", length = 70)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "addr_town", length = 20)
	public String getAddrTown() {
		return this.addrTown;
	}

	public void setAddrTown(String addrTown) {
		this.addrTown = addrTown;
	}

	@Column(name = "addr_postcode", length = 5)
	public String getAddrPostcode() {
		return this.addrPostcode;
	}

	public void setAddrPostcode(String addrPostcode) {
		this.addrPostcode = addrPostcode;
	}

	@Column(name = "addr_state", length = 2)
	public String getAddrState() {
		return this.addrState;
	}

	public void setAddrState(String addrState) {
		this.addrState = addrState;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "addr2", length = 70)
	public String getAddr2() {
		return addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "addr3", length = 70)
	public String getAddr3() {
		return addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	
	
	public boolean compareToMainAddr(RobFormA compareTo){
		if(!convertTrim(compareTo.getBizMainAddr()).equals(convertTrim(getAddr()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddr2()).equals(convertTrim(getAddr2()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddr3()).equals(convertTrim(getAddr3()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddrPostcode()).equals(convertTrim(getAddrPostcode()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddrTown()).equals(convertTrim(getAddrTown()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddrState()).equals(convertTrim(getAddrState()))){
			return false;
		}
		return true;
	}
	
	public boolean compareTo(RobFormABranches compareTo){
		if(!convertTrim(compareTo.getAddr()).equals(convertTrim(getAddr()))){
			return false;
		}
		if(!convertTrim(compareTo.getAddr2()).equals(convertTrim(getAddr2()))){
			return false;
		}
		if(!convertTrim(compareTo.getAddr3()).equals(convertTrim(getAddr3()))){
			return false;
		}
		if(!convertTrim(compareTo.getAddrPostcode()).equals(convertTrim(getAddrPostcode()))){
			return false;
		}
		if(!convertTrim(compareTo.getAddrTown()).equals(convertTrim(getAddrTown()))){
			return false;
		}
		if(!convertTrim(compareTo.getAddrState()).equals(convertTrim(getAddrState()))){
			return false;
		}
		return true;
	}
	
	private String convertTrim(String str){
		if(str==null){
			return "";
		}
		str = str.replaceAll("[^a-zA-Z0-9]", "");
		
		return str;
	}
	
	@Column(name = "addr_url")
	public String getAddrUrl() {
		return addrUrl;
	}

	public void setAddrUrl(String addrUrl) {
		this.addrUrl = addrUrl;
	}
}
