package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 3:52:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * RobFormB2 generated by hbm2java
 */
@Entity
@Audited
@Table(name = "rob_form_b2")
public class RobFormB2 implements java.io.Serializable {

	private long robFormB2Id;
	private Date b2AmmendmendDt;
	private String robFormBCode;
	private String bizDesc;
	private Long formB2DocId;
	private String isHasFormB2Doc;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	
	private List<RobFormB2Det> listRobFormB2Det;

	public RobFormB2() {
	}

	public RobFormB2(long robFormB2Id, String robFormBCode, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormB2Id = robFormB2Id;
		this.robFormBCode = robFormBCode;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobFormB2(long robFormB2Id, String robFormBCode, String bizDesc, Long formB2DocId, String isHasFormB2Doc,
			Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormB2Id = robFormB2Id;
		this.robFormBCode = robFormBCode;
		this.bizDesc = bizDesc;
		this.formB2DocId = formB2DocId;
		this.isHasFormB2Doc = isHasFormB2Doc;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_form_b2_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormB2Id() {
		return this.robFormB2Id;
	}

	public void setRobFormB2Id(long robFormB2Id) {
		this.robFormB2Id = robFormB2Id;
	}

	@Column(name = "rob_form_b_code", nullable = false, length = 25)
	public String getRobFormBCode() {
		return this.robFormBCode;
	}

	public void setRobFormBCode(String robFormBCode) {
		this.robFormBCode = robFormBCode;
	}

	@Column(name = "biz_desc", length = 1500)
	public String getBizDesc() {
		return this.bizDesc;
	}

	public void setBizDesc(String bizDesc) {
		this.bizDesc = bizDesc;
	}

	@Column(name = "form_b2_doc_id")
	public Long getFormB2DocId() {
		return this.formB2DocId;
	}

	public void setFormB2DocId(Long formB2DocId) {
		this.formB2DocId = formB2DocId;
	}

	@Column(name = "is_has_form_b2_doc", length = 1)
	public String getIsHasFormB2Doc() {
		return this.isHasFormB2Doc;
	}

	public void setIsHasFormB2Doc(String isHasFormB2Doc) {
		this.isHasFormB2Doc = isHasFormB2Doc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "robFormBCode")
	@OrderBy("robFormB2DetId ASC")
	public List<RobFormB2Det> getListRobFormB2Det() {
		return listRobFormB2Det;
	}

	public void setListRobFormB2Det(List<RobFormB2Det> listRobFormB2Det) {
		this.listRobFormB2Det = listRobFormB2Det;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "b2_ammendmend_dt", length = 2052)
	public Date getB2AmmendmendDt() {
		return b2AmmendmendDt;
	}

	public void setB2AmmendmendDt(Date b2AmmendmendDt) {
		this.b2AmmendmendDt = b2AmmendmendDt;
	}


}
