package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 3:52:32 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;
import org.hibernate.envers.Audited;

import com.ssm.webis.param.RobFormMainInfo;

/**
 * RobFormB1 generated by hbm2java
 */
@Entity
@Audited
@Table(name = "rob_form_b1")
public class RobFormB1 implements java.io.Serializable {

	private long robFormB1Id;
	private Date b1AmmendmendDt;
	private String robFormBCode;
	private String bizMainAddr;
	private String bizMainAddr2;
	private String bizMainAddr3;
	private String bizMainAddrTown;
	private String bizMainAddrPostcode;
	private String bizMainAddrState;
	private String bizMainAddrTelNo;
	private String bizMainAddrMobileNo;
	private String bizMainAddrEmail;
	private String bizMainAddrUrl;
	private Boolean isMainAddSamePostAddr = Boolean.FALSE;	
	private String bizPostAddr;
	private String bizPostAddr2;
	private String bizPostAddr3;
	private String bizPostAddrTown;
	private String bizPostAddrState;
	private String bizPostAddrPostcode;
	private String bizPostAddrTelNo;
	private String bizPostAddrMobileNo;
	private String bizPostAddrEmail;
//	private String bizMainAddrTownTmp;
//	private String bizPostAddrTownTmp;
//	private String bizMainAddrStateDesc;
//	private String bizPostAddrStateDesc;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public RobFormB1() {
	}

	public RobFormB1(long robFormB1Id, String robFormBCode, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robFormB1Id = robFormB1Id;
		this.robFormBCode = robFormBCode;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobFormB1(long robFormB1Id, String robFormBCode, String bizMainAddr, String bizMainAddrTown,
			String bizMainAddrPostcode, String bizMainAddrState, String bizMainAddrTelNo, String bizMainAddrMobileNo, String bizMainAddrEmail,
			Boolean isMainAddSamePostAddr, String bizPostAddr, String bizPostAddrTown, String bizPostAddrState, String bizPostAddrPostcode,
			String bizPostAddrTelNo, String bizPostAddrMobileNo, String bizPostAddrEmail, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.robFormB1Id = robFormB1Id;
		this.robFormBCode = robFormBCode;
		this.bizMainAddr = bizMainAddr;
		this.bizMainAddrTown = bizMainAddrTown;
		this.bizMainAddrPostcode = bizMainAddrPostcode;
		this.bizMainAddrState = bizMainAddrState;
		this.bizMainAddrTelNo = bizMainAddrTelNo;
		this.bizMainAddrMobileNo = bizMainAddrMobileNo;
		this.bizMainAddrEmail = bizMainAddrEmail;
		this.isMainAddSamePostAddr = isMainAddSamePostAddr;
		this.bizPostAddr = bizPostAddr;
		this.bizPostAddrTown = bizPostAddrTown;
		this.bizPostAddrState = bizPostAddrState;
		this.bizPostAddrPostcode = bizPostAddrPostcode;
		this.bizPostAddrTelNo = bizPostAddrTelNo;
		this.bizPostAddrMobileNo = bizPostAddrMobileNo;
		this.bizPostAddrEmail = bizPostAddrEmail;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_form_b1_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobFormB1Id() {
		return this.robFormB1Id;
	}

	public void setRobFormB1Id(long robFormB1Id) {
		this.robFormB1Id = robFormB1Id;
	}

	@Column(name = "rob_form_b_code", nullable = false, length = 25)
	public String getRobFormBCode() {
		return this.robFormBCode;
	}

	public void setRobFormBCode(String robFormBCode) {
		this.robFormBCode = robFormBCode;
	}

	@Column(name = "biz_main_addr", length = 70)
	public String getBizMainAddr() {
		return this.bizMainAddr;
	}

	public void setBizMainAddr(String bizMainAddr) {
		this.bizMainAddr = bizMainAddr;
	}

	@Column(name = "biz_main_addr_town", length = 20)
	public String getBizMainAddrTown() {
		return this.bizMainAddrTown;
	}

	public void setBizMainAddrTown(String bizMainAddrTown) {
		this.bizMainAddrTown = bizMainAddrTown;
	}

	@Column(name = "biz_main_addr_postcode", length = 5)
	public String getBizMainAddrPostcode() {
		return this.bizMainAddrPostcode;
	}

	public void setBizMainAddrPostcode(String bizMainAddrPostcode) {
		this.bizMainAddrPostcode = bizMainAddrPostcode;
	}

	@Column(name = "biz_main_addr_state", length = 2)
	public String getBizMainAddrState() {
		return this.bizMainAddrState;
	}

	public void setBizMainAddrState(String bizMainAddrState) {
		this.bizMainAddrState = bizMainAddrState;
	}

	@Column(name = "biz_main_addr_tel_no", length = 11)
	public String getBizMainAddrTelNo() {
		return this.bizMainAddrTelNo;
	}

	public void setBizMainAddrTelNo(String bizMainAddrTelNo) {
		this.bizMainAddrTelNo = bizMainAddrTelNo;
	}

	@Column(name = "biz_main_addr_mobile_no", length = 11)
	public String getBizMainAddrMobileNo() {
		return this.bizMainAddrMobileNo;
	}

	public void setBizMainAddrMobileNo(String bizMainAddrMobileNo) {
		this.bizMainAddrMobileNo = bizMainAddrMobileNo;
	}

	@Column(name = "biz_main_addr_email", length = 30)
	public String getBizMainAddrEmail() {
		return this.bizMainAddrEmail;
	}

	public void setBizMainAddrEmail(String bizMainAddrEmail) {
		this.bizMainAddrEmail = bizMainAddrEmail;
	}

	@Column(name = "is_main_add_same_post_addr")
	public Boolean getIsMainAddSamePostAddr() {
		return this.isMainAddSamePostAddr;
	}

	public void setIsMainAddSamePostAddr(Boolean isMainAddSamePostAddr) {
		this.isMainAddSamePostAddr = isMainAddSamePostAddr;
	}

	@Column(name = "biz_post_addr", length = 70)
	public String getBizPostAddr() {
		return this.bizPostAddr;
	}

	public void setBizPostAddr(String bizPostAddr) {
		this.bizPostAddr = bizPostAddr;
	}

	@Column(name = "biz_post_addr_town", length = 20)
	public String getBizPostAddrTown() {
		return this.bizPostAddrTown;
	}

	public void setBizPostAddrTown(String bizPostAddrTown) {
		this.bizPostAddrTown = bizPostAddrTown;
	}

	@Column(name = "biz_post_addr_state", length = 2)
	public String getBizPostAddrState() {
		return this.bizPostAddrState;
	}

	public void setBizPostAddrState(String bizPostAddrState) {
		this.bizPostAddrState = bizPostAddrState;
	}

	@Column(name = "biz_post_addr_postcode", length = 5)
	public String getBizPostAddrPostcode() {
		return this.bizPostAddrPostcode;
	}

	public void setBizPostAddrPostcode(String bizPostAddrPostcode) {
		this.bizPostAddrPostcode = bizPostAddrPostcode;
	}

	@Column(name = "biz_post_addr_tel_no", length = 11)
	public String getBizPostAddrTelNo() {
		return this.bizPostAddrTelNo;
	}

	public void setBizPostAddrTelNo(String bizPostAddrTelNo) {
		this.bizPostAddrTelNo = bizPostAddrTelNo;
	}

	@Column(name = "biz_post_addr_mobile_no", length = 11)
	public String getBizPostAddrMobileNo() {
		return this.bizPostAddrMobileNo;
	}

	public void setBizPostAddrMobileNo(String bizPostAddrMobileNo) {
		this.bizPostAddrMobileNo = bizPostAddrMobileNo;
	}

	@Column(name = "biz_post_addr_email", length = 30)
	public String getBizPostAddrEmail() {
		return this.bizPostAddrEmail;
	}

	public void setBizPostAddrEmail(String bizPostAddrEmail) {
		this.bizPostAddrEmail = bizPostAddrEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "biz_main_addr2", length = 70)
	public String getBizMainAddr2() {
		return bizMainAddr2;
	}

	public void setBizMainAddr2(String bizMainAddr2) {
		this.bizMainAddr2 = bizMainAddr2;
	}

	@Column(name = "biz_main_addr3", length = 70)
	public String getBizMainAddr3() {
		return bizMainAddr3;
	}

	public void setBizMainAddr3(String bizMainAddr3) {
		this.bizMainAddr3 = bizMainAddr3;
	}

	@Column(name = "biz_post_addr2", length = 70)
	public String getBizPostAddr2() {
		return bizPostAddr2;
	}

	public void setBizPostAddr2(String bizPostAddr2) {
		this.bizPostAddr2 = bizPostAddr2;
	}

	@Column(name = "biz_post_addr3", length = 70)
	public String getBizPostAddr3() {
		return bizPostAddr3;
	}

	public void setBizPostAddr3(String bizPostAddr3) {
		this.bizPostAddr3 = bizPostAddr3;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "b1_ammendmend_dt", length = 2052)
	public Date getB1AmmendmendDt() {
		return b1AmmendmendDt;
	}

	public void setB1AmmendmendDt(Date b1AmmendmendDt) {
		this.b1AmmendmendDt = b1AmmendmendDt;
	}

	public boolean compareToCurrentAddress(RobFormMainInfo compareTo) {
		if(!convertTrim(compareTo.getBizMainAddr()).equals(convertTrim(getBizMainAddr()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddr2()).equals(convertTrim(getBizMainAddr2()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddr3()).equals(convertTrim(getBizMainAddr3()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddrPostcode()).equals(convertTrim(getBizMainAddrPostcode()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddrTown()).equals(convertTrim(getBizMainAddrTown()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizMainAddrState()).equals(convertTrim(getBizMainAddrState()))){
			return false;
		}
		
		if(!convertTrim(compareTo.getBizPostAddr()).equals(convertTrim(getBizPostAddr()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizPostAddr2()).equals(convertTrim(getBizPostAddr2()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizPostAddr3()).equals(convertTrim(getBizPostAddr3()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizPostAddrPostcode()).equals(convertTrim(getBizPostAddrPostcode()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizPostAddrTown()).equals(convertTrim(getBizPostAddrTown()))){
			return false;
		}
		if(!convertTrim(compareTo.getBizPostAddrState()).equals(convertTrim(getBizPostAddrState()))){
			return false;
		}
		
		return true;
	}
	
	private String convertTrim(String str){
		if(str==null){
			return "";
		}
		str = str.replaceAll("[^a-zA-Z0-9]", "");
		return str;
	}
	
	@Column(name = "biz_main_addr_url") 
	public String getBizMainAddrUrl() {
		return bizMainAddrUrl;
	}

	public void setBizMainAddrUrl(String bizMainAddrUrl) {
		this.bizMainAddrUrl = bizMainAddrUrl;
	}

//	@Transient
//	public String getBizMainAddrTownTmp() {
//		return bizMainAddrTownTmp;
//	}
//
//	public void setBizMainAddrTownTmp(String bizMainAddrTownTmp) {
//		this.bizMainAddrTownTmp = bizMainAddrTownTmp;
//	}
//
//	@Transient
//	public String getBizPostAddrTownTmp() {
//		return bizPostAddrTownTmp;
//	}
//
//	public void setBizPostAddrTownTmp(String bizPostAddrTownTmp) {
//		this.bizPostAddrTownTmp = bizPostAddrTownTmp;
//	}
//
//	@Transient
//	public String getBizMainAddrStateDesc() {
//		return bizMainAddrStateDesc;
//	}
//
//	public void setBizMainAddrStateDesc(String bizMainAddrStateDesc) {
//		this.bizMainAddrStateDesc = bizMainAddrStateDesc;
//	}
//
//	@Transient
//	public String getBizPostAddrStateDesc() {
//		return bizPostAddrStateDesc;
//	}
//
//	public void setBizPostAddrStateDesc(String bizPostAddrStateDesc) {
//		this.bizPostAddrStateDesc = bizPostAddrStateDesc;
//	}


}
