package com.ssm.llp.ezbiz.model;

// Generated Dec 6, 2012 7:31:52 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Rocbusinessobjectcode generated by hbm2java
 */
@Entity
@Table(name = "rocbusinessobjectcode")
public class RocBusinessObjectCode implements java.io.Serializable {

	private String vchbusinesscode;
	private String vchbusinessdescmalay;
	private String vchbusinessdesceng;
	private String chrstatus;
	private String vchcreateby;
	private Date dtcreatedate;
	private String vchupdateby;
	private Date dtupdatedate;
	private String vchipaddress;
	private String vchbusinesscodeold;
	private String vchstdref;
	private Boolean selected = Boolean.FALSE;


	public RocBusinessObjectCode() {
	}

	public RocBusinessObjectCode(String vchcreateby, Date dtcreatedate,
			String vchupdateby, Date dtupdatedate) {
		this.vchcreateby = vchcreateby;
		this.dtcreatedate = dtcreatedate;
		this.vchupdateby = vchupdateby;
		this.dtupdatedate = dtupdatedate;
	}

	public RocBusinessObjectCode(String vchbusinesscode,
			String vchbusinessdescmalay, String vchbusinessdesceng,
			String chrstatus, String vchcreateby, Date dtcreatedate,
			String vchupdateby, Date dtupdatedate, String vchipaddress,
			String vchbusinesscodeold, String vchstdref) {
		this.vchbusinesscode = vchbusinesscode;
		this.vchbusinessdescmalay = vchbusinessdescmalay;
		this.vchbusinessdesceng = vchbusinessdesceng;
		this.chrstatus = chrstatus;
		this.vchcreateby = vchcreateby;
		this.dtcreatedate = dtcreatedate;
		this.vchupdateby = vchupdateby;
		this.dtupdatedate = dtupdatedate;
		this.vchipaddress = vchipaddress;
		this.vchbusinesscodeold = vchbusinesscodeold;
		this.vchstdref = vchstdref;
	}

	@Id
	@Column(name = "vchbusinesscode", length = 6)
	public String getVchbusinesscode() {
		return this.vchbusinesscode;
	}

	public void setVchbusinesscode(String vchbusinesscode) {
		this.vchbusinesscode = vchbusinesscode;
	}

	@Column(name = "vchbusinessdescmalay", length = 200)
	public String getVchbusinessdescmalay() {
		return this.vchbusinessdescmalay;
	}

	public void setVchbusinessdescmalay(String vchbusinessdescmalay) {
		this.vchbusinessdescmalay = vchbusinessdescmalay;
	}

	@Column(name = "vchbusinessdesceng", length = 200)
	public String getVchbusinessdesceng() {
		return this.vchbusinessdesceng;
	}

	public void setVchbusinessdesceng(String vchbusinessdesceng) {
		this.vchbusinessdesceng = vchbusinessdesceng;
	}

	@Column(name = "chrstatus", length = 1)
	public String getChrstatus() {
		return this.chrstatus;
	}

	public void setChrstatus(String chrstatus) {
		this.chrstatus = chrstatus;
	}

	@Column(name = "vchcreateby", nullable = false, length = 10)
	public String getVchcreateby() {
		return this.vchcreateby;
	}

	public void setVchcreateby(String vchcreateby) {
		this.vchcreateby = vchcreateby;
	}

	@Column(name = "dtcreatedate", nullable = false, length = 3594)
	public Date getDtcreatedate() {
		return this.dtcreatedate;
	}

	public void setDtcreatedate(Date dtcreatedate) {
		this.dtcreatedate = dtcreatedate;
	}

	@Column(name = "vchupdateby", nullable = false, length = 10)
	public String getVchupdateby() {
		return this.vchupdateby;
	}

	public void setVchupdateby(String vchupdateby) {
		this.vchupdateby = vchupdateby;
	}

	@Column(name = "dtupdatedate", nullable = false, length = 3594)
	public Date getDtupdatedate() {
		return this.dtupdatedate;
	}

	public void setDtupdatedate(Date dtupdatedate) {
		this.dtupdatedate = dtupdatedate;
	}

	@Column(name = "vchipaddress", length = 20)
	public String getVchipaddress() {
		return this.vchipaddress;
	}

	public void setVchipaddress(String vchipaddress) {
		this.vchipaddress = vchipaddress;
	}

	@Column(name = "vchbusinesscodeold", length = 6)
	public String getVchbusinesscodeold() {
		return this.vchbusinesscodeold;
	}

	public void setVchbusinesscodeold(String vchbusinesscodeold) {
		this.vchbusinesscodeold = vchbusinesscodeold;
	}

	@Column(name = "vchstdref", length = 30)
	public String getVchstdref() {
		return this.vchstdref;
	}

	public void setVchstdref(String vchstdref) {
		this.vchstdref = vchstdref;
	}
	
	@Transient
	public Boolean getSelected()
	{
		return selected;
	}

	public void setSelected(Boolean selected)
	{
		this.selected = selected;
	}

	
	@Override
	public boolean equals(Object other) {
			if ((this == other))
				return true;
			if ((other == null))
				return false;
			if (!(other instanceof RocBusinessObjectCode))
				return false;
			RocBusinessObjectCode castOther = (RocBusinessObjectCode) other;
			return (this.getVchbusinesscode().equals(castOther.getVchbusinesscode()));
	}

}
