package com.ssm.llp.mod1.model;

// Generated Nov 30, 2012 9:49:47 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.envers.Audited;

/**
 * LlpUserProfile generated by hbm2java
 */
@Entity
@Table(name = "rob_user_profile")
@Audited
public class LlpUserProfile implements java.io.Serializable {

	private String userRefNo;
	private long idRegUser;
	private String userType;
	private String loginId;
	private String userPwd;
	private String email;
	private String add1;
	private String add2;
	private String add3;
	private String country=com.ssm.llp.base.common.Parameter.COUNTRY_CODE_malaysia;
	private String state;
	private String city;
	private String postcode;
	private String hpNo;
	private String offNo;
	private String faxNo;
	private String licenseMbrType;
	private String licenseMbrNo;
	private String name;
	private String idType;
	private String idNo;
	private String icColour;
	private Date idExpiredDt;
	private String nationality;
	private String gender;
	private String race;
	private String othersRace;
	private Date dob;
	private String userStatus;
	private String ipAddress;
	private String remarks;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private String reconfirmPassword;

	
	private String userRefNoNew;
	private String idTypeNew;
	private String idNoNew;
	private String nameNew;
	private String userStatusNew;
	
	private String reTypeEmail;
	
	private String bussinessAdd1;
	private String bussinessAdd2;
	private String bussinessAdd3;
	private String bussinessCountryCode;
	private String bussinessStateCode;
	private String bussinessCity;
	private String bussinessPostcode;
	
	private Boolean declareChk = Boolean.FALSE;
	private String approveBy;
	private String approveByBranch;
	private Date approveDt;
	private String approveChannel= com.ssm.llp.base.common.Parameter.USER_APPROVED_CHANNEL_COUNTER;
	private String isAnsSurvey = com.ssm.llp.base.common.Parameter.YES_NO_no;
	private String isTempPassword = com.ssm.llp.base.common.Parameter.YES_NO_no;
	private Date deceasedDt;
	
	
	public LlpUserProfile() {
	}

	public LlpUserProfile(long idRegUser, String userType, String userId,
			String userPwd, String email, String name, String idType,
			String idNo, String icColour, String nationality, String userStatus, Date createDt,
			String createBy, Date updateDt, String updateBy) {
		this.idRegUser = idRegUser;
		this.userType = userType;
		this.loginId = userId;
		this.userPwd = userPwd;
		this.email = email;
		this.name = name;
		this.idType = idType;
		this.idNo = idNo;
		this.icColour = icColour;
		this.nationality = nationality;
		this.userStatus = userStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpUserProfile(long idRegUser, String userType, String userId,
			String userPwd, String email, String add1, String add2,
			String add3, String country, String state, String city,
			String postcode, String licenseMbrType, String licenseMbrNo,
			String name, String idType, String idNo, String icColour, Date idExpiredDt,
			String nationality, String gender, String race, Date dob,
			String userStatus, String ipAddress, Date createDt,
			String createBy, Date updateDt, String updateBy, String bussinessAdd1, 
			String bussinessAdd2,String bussinessAdd3,
			String bussinessCountryCode,String bussinessStateCode,String bussinessCity,
			String bussinessPostcode, String isAnsSurvey, String isTempPassword) {
		this.idRegUser = idRegUser;
		this.userType = userType;
		this.loginId = userId;
		this.userPwd = userPwd;
		this.email = email;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.country = country;
		this.state = state;
		this.city = city;
		this.postcode = postcode;
		this.licenseMbrType = licenseMbrType;
		this.licenseMbrNo = licenseMbrNo;
		this.name = name;
		this.idType = idType;
		this.idNo = idNo;
		this.icColour = icColour;
		this.idExpiredDt = idExpiredDt;
		this.nationality = nationality;
		this.gender = gender;
		this.race = race;
		this.dob = dob;
		this.userStatus = userStatus;
		this.ipAddress = ipAddress;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.bussinessAdd1=bussinessAdd1;
		this.bussinessAdd2=bussinessAdd2;
		this.bussinessAdd3=bussinessAdd3;
		this.bussinessCountryCode=bussinessCountryCode;
		this.bussinessStateCode=bussinessStateCode;
		this.bussinessCity=bussinessCity;
		this.bussinessPostcode=bussinessPostcode;
		this.isAnsSurvey = isAnsSurvey;
		this.isTempPassword = isTempPassword;
	}

	@Id
    @GenericGenerator(name="ref_no", strategy="com.ssm.llp.base.hibernate.LlpIdGenerator", 
    parameters={@Parameter(name = "genCode", value = "LLP_USER_PROFILE_RUNNING_NO"),
    			@Parameter(name = "fieldCode", value = "EZ"),
    			@Parameter(name = "moduleCode", value = "02"),
    			@Parameter(name = "yearMonthDay", value = "yyyyMMdd"),
    			@Parameter(name = "lastNoPattern", value = "0000")})
    @GeneratedValue(generator="ref_no")
	@Column(name = "user_ref_no", nullable = false, length = 25)
	public String getUserRefNo() {
		return userRefNo;
	}

	public void setUserRefNo(String userRefNo) {
		this.userRefNo = userRefNo;
	}
	
//	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_reg_user", columnDefinition="serial", unique = true, nullable = false, updatable=false,insertable = false)
	public long getIdRegUser() {
		return this.idRegUser;
	}

	public void setIdRegUser(long idRegUser) {
		this.idRegUser = idRegUser;
	}

	@Column(name = "user_type", nullable = false, length = 2)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "user_pwd",  length = 50)
	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@Column(name = "email", nullable = true, length = 50)
	public String getEmail() {
		if(email!=null) {
			return email.toLowerCase();
		}
		return this.email;
	}

	public void setEmail(String email) {
		if(email!=null) {
			email = email.toLowerCase();
		}
		this.email = email;
	}

	@Column(name = "add1", length = 150)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "add2", length = 150)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "add3", length = 150)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "country", length = 4)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 4)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city", length = 150)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postcode", length = 10)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "license_mbr_type", length = 4)
	public String getLicenseMbrType() {
		return this.licenseMbrType;
	}

	public void setLicenseMbrType(String licenseMbrType) {
		this.licenseMbrType = licenseMbrType;
	}

	@Column(name = "license_mbr_no", length = 20)
	public String getLicenseMbrNo() {
		return this.licenseMbrNo;
	}

	public void setLicenseMbrNo(String licenseMbrNo) {
		this.licenseMbrNo = licenseMbrNo;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id_type", nullable = false, length = 4)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	@Column(name = "id_no", nullable = false, length = 20)
	public String getIdNo() {
		return this.idNo;
	}

	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}
	
	@Column(name = "id_color", nullable = false, length = 20)
	public String getIcColour() {
		return this.icColour;
	}

	public void setIcColour(String icColour) {
		this.icColour = icColour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "id_expired_dt", length = 4)
	public Date getIdExpiredDt() {
		return this.idExpiredDt;
	}

	public void setIdExpiredDt(Date idExpiredDt) {
		this.idExpiredDt = idExpiredDt;
	}

	@Column(name = "nationality", nullable = false, length = 4)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "gender", length = 4)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "race", length = 4)
	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dob", length = 4)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "user_status", nullable = false, length = 4)
	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	@Column(name = "ip_address", length = 12)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "hp_no",  length = 15)
	public String getHpNo() {
		return hpNo;
	}

	public void setHpNo(String hpNo) {
		this.hpNo = hpNo;
	}

	@Column(name = "off_no", length = 15)
	public String getOffNo() {
		return offNo;
	}

	public void setOffNo(String offNo) {
		this.offNo = offNo;
	}

	@Column(name = "fax_no", length = 15)
	public String getFaxNo() {
		return faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}
	
	@Column(name = "login_id",  length = 50, unique=true)
	public String getLoginId() {
		if(loginId!=null) {
			return loginId.toUpperCase();
		}
		return loginId;
	}

	public void setLoginId(String loginId) {
		if(loginId!=null) {
			loginId = loginId.toUpperCase();
		}
		this.loginId = loginId;
	}
	
	@Column(name = "remarks", length = 255)
	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Transient
	public String getReconfirmPassword() {
		return reconfirmPassword;
	}

	public void setReconfirmPassword(String reconfirmPassword) {
		this.reconfirmPassword = reconfirmPassword;
	}
	
	@Transient
	public void copyDataFromPartnerLink(LlpPartnerLink llpPartnerLink) { //use in partner page
		setAdd1(llpPartnerLink.getAdd1());
    	setAdd2(llpPartnerLink.getAdd2());
    	setAdd3(llpPartnerLink.getAdd3());
    	setPostcode(llpPartnerLink.getPostcode());
    	setCity(llpPartnerLink.getCity());
    	setState(llpPartnerLink.getState());
    	setCountry(llpPartnerLink.getCountry());
    	setEmail(llpPartnerLink.getEmail());
    	setOffNo(llpPartnerLink.getOffNo());
    	setHpNo(llpPartnerLink.getHpNo());
    	setFaxNo(llpPartnerLink.getFaxNo());
    	
	}
	@Transient
	public String getUserRefNoNew() {
		return userRefNoNew;
	}

	public void setUserRefNoNew(String userRefNoNew) {
		this.userRefNoNew = userRefNoNew;
	}
	@Transient
	public String getIdTypeNew() {
		return idTypeNew;
	}

	public void setIdTypeNew(String idTypeNew) {
		this.idTypeNew = idTypeNew;
	}
	@Transient
	public String getIdNoNew() {
		return idNoNew;
	}

	public void setIdNoNew(String idNoNew) {
		this.idNoNew = idNoNew;
	}
	@Transient
	public String getNameNew() {
		return nameNew;
	}

	public void setNameNew(String nameNew) {
		this.nameNew = nameNew;
	}
	@Transient
	public String getUserStatusNew() {
		return userStatusNew;
	}

	public void setUserStatusNew(String userStatusNew) {
		this.userStatusNew = userStatusNew;
	}
	@Transient
	public String getReTypeEmail() {
		return reTypeEmail;
	}

	public void setReTypeEmail(String reTypeEmail) {
		this.reTypeEmail = reTypeEmail;
	}

	@Column(name = "bussiness_add1", length = 150)
	public String getBussinessAdd1() {
		return bussinessAdd1;
	}

	public void setBussinessAdd1(String bussinessAdd1) {
		this.bussinessAdd1 = bussinessAdd1;
	}

	@Column(name = "bussiness_add2", length = 150)
	public String getBussinessAdd2() {
		return bussinessAdd2;
	}

	public void setBussinessAdd2(String bussinessAdd2) {
		this.bussinessAdd2 = bussinessAdd2;
	}

	@Column(name = "bussiness_add3", length = 150)
	public String getBussinessAdd3() {
		return bussinessAdd3;
	}


	public void setBussinessAdd3(String bussinessAdd3) {
		this.bussinessAdd3 = bussinessAdd3;
	}

	@Column(name = "bussiness_country_code", length = 4) 
	public String getBussinessCountryCode() {
		return bussinessCountryCode;
	}

	public void setBussinessCountryCode(String bussinessCountryCode) {
		this.bussinessCountryCode = bussinessCountryCode;
	}

	@Column(name = "bussiness_state_code", length = 4)
	public String getBussinessStateCode() {
		return bussinessStateCode;
	}

	public void setBussinessStateCode(String bussinessStateCode) {
		this.bussinessStateCode = bussinessStateCode;
	}

	@Column(name = "bussiness_city", length = 150)
	public String getBussinessCity() {
		return bussinessCity;
	}

	public void setBussinessCity(String bussinessCity) {
		this.bussinessCity = bussinessCity;
	}

	@Column(name = "bussiness_postcode", length = 10)
	public String getBussinessPostcode() {
		return bussinessPostcode;
	}

	public void setBussinessPostcode(String bussinessPostcode) {
		this.bussinessPostcode = bussinessPostcode;
	}

	@Transient
	public Boolean getDeclareChk() {
		return declareChk;
	}

	public void setDeclareChk(Boolean declareChk) {
		this.declareChk = declareChk;
	}

	@Column(name = "approve_by", length = 50)
	public String getApproveBy() {
		return approveBy;
	}

	
	public void setApproveBy(String approveBy) {
		this.approveBy = approveBy;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approve_dt", length = 3594)
	public Date getApproveDt() {
		return approveDt;
	}

	public void setApproveDt(Date approveDt) {
		this.approveDt = approveDt;
	}

	@Column(name = "approve_channel", length = 10)
	public String getApproveChannel() {
		return approveChannel;
	}

	public void setApproveChannel(String approveChannel) {
		this.approveChannel = approveChannel;
	}

	@Column(name = "others_race", length = 50)
	public String getOthersRace() {
		return othersRace;
	}

	public void setOthersRace(String othersRace) {
		this.othersRace = othersRace;
	}

	@Column(name = "is_ans_survey")
	public String getIsAnsSurvey() {
		return isAnsSurvey;
	}

	public void setIsAnsSurvey(String isAnsSurvey) {
		this.isAnsSurvey = isAnsSurvey;
	}

	@Column(name = "is_temp_password")
	public String getIsTempPassword() {
		return isTempPassword;
	}

	public void setIsTempPassword(String isTempPassword) {
		this.isTempPassword = isTempPassword;
	}


	@Column(name = "approve_by_branch", length = 10)
	public String getApproveByBranch() {
		return approveByBranch;
	}

	public void setApproveByBranch(String approveByBranch) {
		this.approveByBranch = approveByBranch;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deceased_dt", length = 4)
	public Date getDeceasedDt() {
		return deceasedDt;
	}

	public void setDeceasedDt(Date deceasedDt) {
		this.deceasedDt = deceasedDt;
	}
	


}
