package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 3:01:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.apache.wicket.markup.html.form.upload.FileUpload;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.envers.Audited;

import com.ssm.webis.param.BizProfileDetResp;

/**
 * RobFormC generated by hbm2java
 */
@Entity
@Audited
@Table(name = "rob_form_c")
public class RobFormC implements java.io.Serializable {

	private String robFormCCode;
	private String brNo;
	private String checkDigit;
	private String bizName;
	private String status;
	private String reasonType=com.ssm.llp.base.common.Parameter.ROB_FORM_C_REASON_H;
	private String reasonOthers;
	private Date deceasedDt;
	private Date terminationDt;
	private Date courtOrderDt;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private double cmpAmt;
	private double bizInfoAmt;
	private double totalAmt;
	private Long businessInfoDataId;
	private Long formCDataId;
	private Long cmpDataId;
	private String approveRejectNotes;
	private Date approveRejectDt;
	private String prosessingBranch;
	private String approveRejectBranch;
	private String approveRejectBy;
	private String isFromSSMPc =  com.ssm.llp.base.common.Parameter.YES_NO_no;
	private long rowVersion;
	

	private String isBuyInfo=com.ssm.llp.base.common.Parameter.YES_NO_yes;
	private String isPayCmp=com.ssm.llp.base.common.Parameter.YES_NO_no;
	private String cmpNo;
	private double gstAmt;
	private Date submitDt;
	private Date resubmitDt;
	private Date paymentDt;
	private Long supportingDocId;
	private String isHasSupportingDoc=com.ssm.llp.base.common.Parameter.YES_NO_no;
	private boolean isAttachmentExceedSize = false;
	private boolean isNotPdf = false;
	
	private BizProfileDetResp bizProfileDetResp;
	
	private List<RobFormOwnerVerification> listRobFormOwnerVerification = new ArrayList<RobFormOwnerVerification>(0);
	private List<RobFormNotes> listRobFormNotes = new ArrayList<RobFormNotes>(0);
	
	
	private String page;
	private Boolean declarationChkBox = Boolean.FALSE;
	private String queryAnswer;
	
	private List<FileUpload> fileUploadTmp;
	

	@Transient
	public List<FileUpload> getFileUploadTmp() {
		return fileUploadTmp;
	}

	public void setFileUploadTmp(List<FileUpload> fileUploadTmp) {
		this.fileUploadTmp = fileUploadTmp;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "robFormCode")
	@OrderBy("robFormNoteId ASC")
	public List<RobFormNotes> getListRobFormNotes() {
		return listRobFormNotes;
	}

	public void setListRobFormNotes(List<RobFormNotes> listRobFormNotes) {
		this.listRobFormNotes = listRobFormNotes;
	}


	

	@Transient
	public String getQueryAnswer() {
		return queryAnswer;
	}

	public void setQueryAnswer(String queryAnswer) {
		this.queryAnswer = queryAnswer;
	}

	public void copyFrom(RobFormC robFormCForm) {
		this.brNo= robFormCForm.getBrNo();
		this.bizName= robFormCForm.getBizName();
		this.checkDigit=robFormCForm.getCheckDigit();
		this.status=robFormCForm.getStatus();
		this.reasonType=robFormCForm.getReasonType();
		this.reasonOthers=robFormCForm.getReasonOthers();
		//this.deceasedDt=robFormCForm.getDeceasedDt();
		this.terminationDt=robFormCForm.getTerminationDt();
	//	this.courtOrderDt=robFormCForm.getCourtOrderDt();
		//this.cmpAmt=robFormCForm.getCmpAmt();
		this.bizInfoAmt=robFormCForm.getBizInfoAmt();
		this.isBuyInfo=robFormCForm.getIsBuyInfo();
		this.gstAmt=robFormCForm.getGstAmt();
		
		//this.isPayCmp=robFormCForm.getIsPayCmp();
		this.cmpAmt=robFormCForm.getCmpAmt();
		this.totalAmt=robFormCForm.getTotalAmt();
		this.queryAnswer=robFormCForm.getQueryAnswer();
		this.fileUploadTmp=robFormCForm.getFileUploadTmp();
		
		
	}
	
	@Transient
	public Boolean getDeclarationChkBox() {
		return declarationChkBox;
	}

	public void setDeclarationChkBox(Boolean declarationChkBox) {
		this.declarationChkBox = declarationChkBox;
	}


	@Transient
	public String getPage() {
		return page;
	}



	public void setPage(String page) {
		this.page = page;
	}

	@Transient
	public List<RobFormOwnerVerification> getListRobFormOwnerVerification() {
		return listRobFormOwnerVerification;
	}

	public void setListRobFormOwnerVerification(
			List<RobFormOwnerVerification> listRobFormOwnerVerification) {
		this.listRobFormOwnerVerification = listRobFormOwnerVerification;
	}

	@Transient
	public BizProfileDetResp getBizProfileDetResp() {
		return bizProfileDetResp;
	}

	public void setBizProfileDetResp(BizProfileDetResp bizProfileDetResp) {
		this.bizProfileDetResp = bizProfileDetResp;
	}
	
	

	public RobFormC() {
	}

	public RobFormC(String robFormCCode, Date deceasedDt, Date terminationDt, Date courtOrderDt, Date createDt, String createBy, Date updateDt,
			String updateBy, Date paymentDt) {
		this.robFormCCode = robFormCCode;
		this.deceasedDt = deceasedDt;
		this.terminationDt = terminationDt;
		this.courtOrderDt = courtOrderDt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.paymentDt=paymentDt;
	}

	public RobFormC(String robFormCCode, String brNo, String checkDigit, String bizName, String status, String reasonType, String reasonOthers,
			Date deceasedDt, Date terminationDt, Date courtOrderDt, Date createDt, String createBy, Date updateDt, String updateBy, double cmpAmt,
			double bizInfoAmt, double totalAmt, Long businessInfoDataId, Long formCDataId, String isBuyInfo, String isPayCmp, String cmpNo,
			double gstAmt, Date submitDt, Date resubmitDt, Date paymentDt,Long supportingDocId, String isHasSupportingDoc) {
		this.robFormCCode = robFormCCode;
		this.brNo = brNo;
		this.checkDigit = checkDigit;
		this.bizName = bizName;
		this.status = status;
		this.reasonType = reasonType;
		this.reasonOthers = reasonOthers;
		this.deceasedDt = deceasedDt;
		this.terminationDt = terminationDt;
		this.courtOrderDt = courtOrderDt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.cmpAmt = cmpAmt;
		this.bizInfoAmt = bizInfoAmt;
		this.totalAmt = totalAmt;
		this.businessInfoDataId = businessInfoDataId;
		this.formCDataId = formCDataId;
		this.isBuyInfo = isBuyInfo;
		this.isPayCmp = isPayCmp;
		this.cmpNo = cmpNo;
		this.gstAmt = gstAmt;
		this.submitDt = submitDt;
		this.resubmitDt = resubmitDt;
		this.paymentDt=paymentDt;
		this.supportingDocId = supportingDocId;
		this.isHasSupportingDoc = isHasSupportingDoc;
	}

	@Id
    @GenericGenerator(name="ref_no", strategy="com.ssm.llp.base.hibernate.LlpIdGenerator", 
    parameters={@Parameter(name = "genCode", value = "ROB_FORM_C_RUNNING_NO"),
    			@Parameter(name = "fieldCode", value = "EB"),
    			@Parameter(name = "moduleCode", value = "-C"),
    			@Parameter(name = "yearMonthDay", value = "yyyyMMdd"),
    			@Parameter(name = "lastNoPattern", value = "00000")})
    @GeneratedValue(generator="ref_no")
	@Column(name = "rob_form_c_code", nullable = false, length = 25)
	public String getRobFormCCode() {
		return this.robFormCCode;
	}

	public void setRobFormCCode(String robFormCCode) {
		this.robFormCCode = robFormCCode;
	}

	@Column(name = "br_no", length = 20)
	public String getBrNo() {
		return this.brNo;
	}

	public void setBrNo(String brNo) {
		this.brNo = brNo;
	}

	@Column(name = "check_digit", length = 1)
	public String getCheckDigit() {
		return this.checkDigit;
	}

	public void setCheckDigit(String checkDigit) {
		this.checkDigit = checkDigit;
	}

	@Column(name = "biz_name", length = 100)
	public String getBizName() {
		return this.bizName;
	}

	public void setBizName(String bizName) {
		this.bizName = bizName;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "reason_type", length = 10)
	public String getReasonType() {
		return this.reasonType;
	}

	public void setReasonType(String reasonType) {
		this.reasonType = reasonType;
	}

	@Column(name = "reason_others")
	public String getReasonOthers() {
		return this.reasonOthers;
	}

	public void setReasonOthers(String reasonOthers) {
		this.reasonOthers = reasonOthers;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deceased_dt",length = 2052)
	public Date getDeceasedDt() {
		return this.deceasedDt;
	}

	public void setDeceasedDt(Date deceasedDt) {
		this.deceasedDt = deceasedDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "termination_dt", nullable = false, length = 2052)
	public Date getTerminationDt() {
		return this.terminationDt;
	}

	public void setTerminationDt(Date terminationDt) {
		this.terminationDt = terminationDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "court_order_dt", length = 2052)
	public Date getCourtOrderDt() {
		return this.courtOrderDt;
	}

	public void setCourtOrderDt(Date courtOrderDt) {
		this.courtOrderDt = courtOrderDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "cmp_amt", precision = 16)
	public double getCmpAmt() {
		return this.cmpAmt;
	}

	public void setCmpAmt(double cmpAmt) {
		this.cmpAmt = cmpAmt;
	}

	@Column(name = "biz_info_amt", precision = 16)
	public double getBizInfoAmt() {
		return this.bizInfoAmt;
	}

	public void setBizInfoAmt(double bizInfoAmt) {
		this.bizInfoAmt = bizInfoAmt;
	}

	@Column(name = "total_amt", precision = 16)
	public double getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(double totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "business_info_data_id")
	public Long getBusinessInfoDataId() {
		return this.businessInfoDataId;
	}

	public void setBusinessInfoDataId(Long businessInfoDataId) {
		this.businessInfoDataId = businessInfoDataId;
	}

	@Column(name = "form_c_data_id")
	public Long getFormCDataId() {
		return this.formCDataId;
	}

	public void setFormCDataId(Long formCDataId) {
		this.formCDataId = formCDataId;
	}

	@Column(name = "is_buy_info", length = 1)
	public String getIsBuyInfo() {
		return this.isBuyInfo;
	}

	public void setIsBuyInfo(String isBuyInfo) {
		this.isBuyInfo = isBuyInfo;
	}

	@Column(name = "is_pay_cmp", length = 1)
	public String getIsPayCmp() {
		return this.isPayCmp;
	}

	public void setIsPayCmp(String isPayCmp) {
		this.isPayCmp = isPayCmp;
	}

	@Column(name = "cmp_no", length = 50)
	public String getCmpNo() {
		return this.cmpNo;
	}

	public void setCmpNo(String cmpNo) {
		this.cmpNo = cmpNo;
	}

	@Column(name = "gst_amt", precision = 16)
	public double getGstAmt() {
		return this.gstAmt;
	}

	public void setGstAmt(double gstAmt) {
		this.gstAmt = gstAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submit_dt", length = 3594)
	public Date getSubmitDt() {
		return this.submitDt;
	}

	public void setSubmitDt(Date submitDt) {
		this.submitDt = submitDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "resubmit_dt", length = 3594)
	public Date getResubmitDt() {
		return this.resubmitDt;
	}

	public void setResubmitDt(Date resubmitDt) {
		this.resubmitDt = resubmitDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_dt", length = 3594)
	public Date getPaymentDt() {
		return paymentDt;
	}

	public void setPaymentDt(Date paymentDt) {
		this.paymentDt = paymentDt;
	}
	
	@Column(name = "supporting_doc_id")
	public Long getSupportingDocId() {
		return this.supportingDocId;
	}

	public void setSupportingDocId(Long supportingDocId) {
		this.supportingDocId = supportingDocId;
	}

	@Column(name = "is_has_supporting_doc", length = 1)
	public String getIsHasSupportingDoc() {
		return this.isHasSupportingDoc;
	}

	public void setIsHasSupportingDoc(String isHasSupportingDoc) {
		this.isHasSupportingDoc = isHasSupportingDoc;
	}
	
	@Column(name = "cmp_data_id")
	public Long getCmpDataId() {
		return cmpDataId;
	}

	public void setCmpDataId(Long cmpDataId) {
		this.cmpDataId = cmpDataId;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approve_reject_dt")
	public Date getApproveRejectDt() {
		return approveRejectDt;
	}

	public void setApproveRejectDt(Date approveRejectDt) {
		this.approveRejectDt = approveRejectDt;
	}
	
	@Column(name = "approve_reject_notes")
	public String getApproveRejectNotes() {
		return approveRejectNotes;
	}

	public void setApproveRejectNotes(String approveRejectNotes) {
		this.approveRejectNotes = approveRejectNotes;
	}
	

	@Column(name = "prosessing_branch", length = 5)
	public String getProsessingBranch() {
		return prosessingBranch;
	}

	public void setProsessingBranch(String prosessingBranch) {
		this.prosessingBranch = prosessingBranch;
	}

	@Transient
	public boolean isAttachmentExceedSize() {
		return isAttachmentExceedSize;
	}
	
	public void setAttachmentExceedSize(boolean isAttachmentExceedSize) {
		this.isAttachmentExceedSize = isAttachmentExceedSize;
	}

	@Transient
	public boolean isNotPdf() {
		return isNotPdf;
	}

	public void setNotPdf(boolean isNotPdf) {
		this.isNotPdf = isNotPdf;
	}
	
	@Version
	@Column(name = "row_version")
	public long getRowVersion() {
		return rowVersion;
	}

	public void setRowVersion(long rowVersion) {
		this.rowVersion = rowVersion;
	}


	@Column(name = "approve_reject_branch")
	public String getApproveRejectBranch() {
		return approveRejectBranch;
	}

	public void setApproveRejectBranch(String approveRejectBranch) {
		this.approveRejectBranch = approveRejectBranch;
	}

	@Column(name = "approve_reject_by")
	public String getApproveRejectBy() {
		return approveRejectBy;
	}

	public void setApproveRejectBy(String approveRejectBy) {
		this.approveRejectBy = approveRejectBy;
	}
	
	@Column(name = "is_from_ssm_pc") 
	public String getIsFromSSMPc() {
		return isFromSSMPc;
	}

	public void setIsFromSSMPc(String isFromSSMPc) {
		this.isFromSSMPc = isFromSSMPc;
	}
	
	@Transient
	public String getBrNoWithCheckDigit() {
		return getBrNo()+"-"+getCheckDigit();
	}
}
