package com.ssm.llp.base.common.model;

// Generated Jan 8, 2013 11:24:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LlpAppsvrNode generated by hbm2java
 */
@Entity
@Table(name = "rob_appsvr_node")
public class LlpAppsvrNode implements java.io.Serializable {

	private long nodeId;
	private String nodeSvrUrl;

	public LlpAppsvrNode() {
	}

	public LlpAppsvrNode(long nodeId) {
		this.nodeId = nodeId;
	}

	public LlpAppsvrNode(long nodeId, String nodeSvrUrl) {
		this.nodeId = nodeId;
		this.nodeSvrUrl = nodeSvrUrl;
	}

	@Id
	@Column(name = "node_id", unique = true, nullable = false)
	public long getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(long nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "node_svr_url")
	public String getNodeSvrUrl() {
		return this.nodeSvrUrl;
	}

	public void setNodeSvrUrl(String nodeSvrUrl) {
		this.nodeSvrUrl = nodeSvrUrl;
	}

}
