package com.ssm.llp.ezbiz.model;

// Generated Jan 14, 2016 10:52:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.apache.wicket.markup.html.form.upload.FileUpload;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;

import com.ssm.llp.base.common.model.LlpFileData;

/**
 * RobFormA generated by hbm2java
 */
@Entity
@Table(name = "rob_form_a")
@Audited
public class RobFormA implements java.io.Serializable {

	private String robFormACode;
	private String brNo;
	private String nameType;
	private String bizName;
	private String bizDesc;
	private Date bizStartDt;
	private Short bizRegPeriod;
	private Boolean isHasPartnershipAgreement = Boolean.FALSE;	
	private Date bizPartnershipAgreementDate;
	private String bizMainAddr;
	private String bizMainAddr2;
	private String bizMainAddr3;
	private String bizMainAddrTown;
	private String bizMainAddrPostcode;
	private String bizMainAddrState;
	private String bizMainAddrTelNo;
	private String bizMainAddrMobileNo;
	private String bizMainAddrEmail;
	private String bizMainAddrUrl;
	private Boolean isMainAddSamePostAddr = Boolean.FALSE;	
	private String bizPostAddr;
	private String bizPostAddr2;
	private String bizPostAddr3;
	private String bizPostAddrTown;
	private String bizPostAddrState;
	private String bizPostAddrPostcode;
	private String bizPostAddrTelNo;
	private String bizPostAddrMobileNo;
	private String bizPostAddrEmail;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private String status;
	private String queryAnswer;
	private double registrationAmt;
	private double branchesAmt;
	private double totalAmt;
	private double gstAmt;
	private long rowVersion;
	private LlpFileData certFileData;
	private LlpFileData businessInfoData;
	private LlpFileData formAData;
	private LlpFileData supportingDocData;
	private LlpFileData cmpNoticeFileData;
	private String isBuyInfo = com.ssm.llp.base.common.Parameter.YES_NO_yes;
	private Date submitDt;
	private Date reSubmitDt;
	private String partnerShipAggStr;
	private String isIncubator = com.ssm.llp.base.common.Parameter.YES_NO_no;
	private Date paymentDt;
	private String isHasSupportingDoc;
	private String compoundNo;
	private String isOnlineSeller;
	private String incentive = com.ssm.llp.base.common.Parameter.YES_NO_no;
	private String approveRejectNotes;
	private Date approveRejectDt;
	private String prosessingBranch;
	private String approveRejectBranch;
	private String approveRejectBy;
	private String isFromSSMPc =  com.ssm.llp.base.common.Parameter.YES_NO_no;

	private List<RobFormNotes> listRobFormNotes = new ArrayList<RobFormNotes>(0);
	private List<RobFormABranches> listRobFormABranches = new ArrayList<RobFormABranches>(0);
	private List<RobFormABizCode> listRobFormABizCode = new ArrayList<RobFormABizCode>(0);
	private List<RobFormAOwner> listRobFormAOwner = new ArrayList<RobFormAOwner>(0);
	private List<FileUpload> formAfileUpload;

	
	private String newIcNoForOwners;
	private Boolean declarationChkBox = Boolean.FALSE;
	private double businessInfoAmt;	
		
	public RobFormA() {
	}

	public RobFormA(String robFormACode) {
		this.robFormACode = robFormACode;
	}

	public RobFormA(String robFormACode, String nameType, String bizName, String bizDesc, Date bizStartDt, Short bizRegPeriod,
			String isPartnershipAgreement, Date bizPartnershipAgreementDate, String bizMainAddr, String bizMainAddrTown,
			String bizMainAddrPostcode, String bizMainAddrState, String bizMainAddrTelNo, String bizMainAddrMobileNo,
			String bizMainAddrEmail, boolean isMainAddSamePostAddr, String bizPostAddr, String bizPostAddrTown, String bizPostAddrState,
			String bizPostAddrPostcode, String bizPostAddrTelNo, String bizPostAddrMobileNo, String bizPostAddrEmail, String isOnlineSeller,
			String incentive, Date approveRejectDt, String approveRejectNotes) {
		this.robFormACode = robFormACode;
		this.nameType = nameType;
		this.bizName = bizName;
		this.bizDesc = bizDesc;
		this.bizStartDt = bizStartDt;
		this.bizRegPeriod = bizRegPeriod;
		this.isHasPartnershipAgreement = isHasPartnershipAgreement;
		this.bizPartnershipAgreementDate = bizPartnershipAgreementDate;
		this.bizMainAddr = bizMainAddr;
		this.bizMainAddrTown = bizMainAddrTown;
		this.bizMainAddrPostcode = bizMainAddrPostcode;
		this.bizMainAddrState = bizMainAddrState;
		this.bizMainAddrTelNo = bizMainAddrTelNo;
		this.bizMainAddrMobileNo = bizMainAddrMobileNo;
		this.bizMainAddrEmail = bizMainAddrEmail;
		this.isMainAddSamePostAddr = isMainAddSamePostAddr;
		this.bizPostAddr = bizPostAddr;
		this.bizPostAddrTown = bizPostAddrTown;
		this.bizPostAddrState = bizPostAddrState;
		this.bizPostAddrPostcode = bizPostAddrPostcode;
		this.bizPostAddrTelNo = bizPostAddrTelNo;
		this.bizPostAddrMobileNo = bizPostAddrMobileNo;
		this.bizPostAddrEmail = bizPostAddrEmail;
		this.isOnlineSeller = isOnlineSeller;
		this.incentive = incentive;
		this.approveRejectDt = approveRejectDt;
		this.approveRejectNotes = approveRejectNotes;
	}

	@Id
    @GenericGenerator(name="ref_no", strategy="com.ssm.llp.base.hibernate.LlpIdGenerator", 
    parameters={@Parameter(name = "genCode", value = "ROB_FORM_A_RUNNING_NO"),
    			@Parameter(name = "fieldCode", value = "EB"),
    			@Parameter(name = "moduleCode", value = "-A"),
    			@Parameter(name = "yearMonthDay", value = "yyyyMMdd"),
    			@Parameter(name = "lastNoPattern", value = "00000")})
    @GeneratedValue(generator="ref_no")
	@Column(name = "rob_form_a_code", nullable = false, length = 25)
	public String getRobFormACode() {
		return this.robFormACode;
	}

	public void setRobFormACode(String robFormACode) {
		this.robFormACode = robFormACode;
	}

	@Column(name = "name_type", length = 1)
	public String getNameType() {
		return this.nameType;
	}

	public void setNameType(String nameType) {
		this.nameType = nameType;
	}

	@Column(name = "biz_name", length = 100)
	public String getBizName() {
		return this.bizName;
	}

	public void setBizName(String bizName) {
		this.bizName = bizName;
	}

	@Column(name = "biz_desc", length = 1500)
	public String getBizDesc() {
		return this.bizDesc;
	}

	public void setBizDesc(String bizDesc) {
		this.bizDesc = bizDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "biz_start_dt", length = 2052)
	public Date getBizStartDt() {
		return this.bizStartDt;
	}

	public void setBizStartDt(Date bizStartDt) {
		this.bizStartDt = bizStartDt;
	}

	@Column(name = "biz_reg_period")
	public Short getBizRegPeriod() {
		return this.bizRegPeriod;
	}

	public void setBizRegPeriod(Short bizRegPeriod) {
		this.bizRegPeriod = bizRegPeriod;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "biz_partnership_agreement_date", length = 2052)
	public Date getBizPartnershipAgreementDate() {
		return this.bizPartnershipAgreementDate;
	}

	public void setBizPartnershipAgreementDate(Date bizPartnershipAgreementDate) {
		this.bizPartnershipAgreementDate = bizPartnershipAgreementDate;
	}

	@Column(name = "biz_main_addr", length = 70)
	public String getBizMainAddr() {
		return this.bizMainAddr;
	}

	public void setBizMainAddr(String bizMainAddr) {
		this.bizMainAddr = bizMainAddr;
	}

	@Column(name = "biz_main_addr_town", length = 20)
	public String getBizMainAddrTown() {
		return this.bizMainAddrTown;
	}

	public void setBizMainAddrTown(String bizMainAddrTown) {
		this.bizMainAddrTown = bizMainAddrTown;
	}

	@Column(name = "biz_main_addr_postcode", length = 5)
	public String getBizMainAddrPostcode() {
		return this.bizMainAddrPostcode;
	}

	public void setBizMainAddrPostcode(String bizMainAddrPostcode) {
		this.bizMainAddrPostcode = bizMainAddrPostcode;
	}

	@Column(name = "biz_main_addr_state", length = 2)
	public String getBizMainAddrState() {
		return this.bizMainAddrState;
	}

	public void setBizMainAddrState(String bizMainAddrState) {
		this.bizMainAddrState = bizMainAddrState;
	}

	@Column(name = "biz_main_addr_tel_no", length = 11)
	public String getBizMainAddrTelNo() {
		return this.bizMainAddrTelNo;
	}

	public void setBizMainAddrTelNo(String bizMainAddrTelNo) {
		this.bizMainAddrTelNo = bizMainAddrTelNo;
	}

	@Column(name = "biz_main_addr_mobile_no", length = 11)
	public String getBizMainAddrMobileNo() {
		return this.bizMainAddrMobileNo;
	}

	public void setBizMainAddrMobileNo(String bizMainAddrMobileNo) {
		this.bizMainAddrMobileNo = bizMainAddrMobileNo;
	}

	@Column(name = "biz_main_addr_email", length = 50)
	public String getBizMainAddrEmail() {
		return this.bizMainAddrEmail;
	}

	public void setBizMainAddrEmail(String bizMainAddrEmail) {
		this.bizMainAddrEmail = bizMainAddrEmail;
	}
	

	@Column(name = "biz_post_addr", length = 70)
	public String getBizPostAddr() {
		return this.bizPostAddr;
	}

	public void setBizPostAddr(String bizPostAddr) {
		this.bizPostAddr = bizPostAddr;
	}

	@Column(name = "biz_post_addr_town", length = 20)
	public String getBizPostAddrTown() {
		return this.bizPostAddrTown;
	}

	public void setBizPostAddrTown(String bizPostAddrTown) {
		this.bizPostAddrTown = bizPostAddrTown;
	}

	@Column(name = "biz_post_addr_state", length = 2)
	public String getBizPostAddrState() {
		return this.bizPostAddrState;
	}

	public void setBizPostAddrState(String bizPostAddrState) {
		this.bizPostAddrState = bizPostAddrState;
	}

	@Column(name = "biz_post_addr_postcode", length = 5)
	public String getBizPostAddrPostcode() {
		return this.bizPostAddrPostcode;
	}

	public void setBizPostAddrPostcode(String bizPostAddrPostcode) {
		this.bizPostAddrPostcode = bizPostAddrPostcode;
	}

	@Column(name = "biz_post_addr_tel_no", length = 11)
	public String getBizPostAddrTelNo() {
		return this.bizPostAddrTelNo;
	}

	public void setBizPostAddrTelNo(String bizPostAddrTelNo) {
		this.bizPostAddrTelNo = bizPostAddrTelNo;
	}

	@Column(name = "biz_post_addr_mobile_no", length = 11)
	public String getBizPostAddrMobileNo() {
		return this.bizPostAddrMobileNo;
	}

	public void setBizPostAddrMobileNo(String bizPostAddrMobileNo) {
		this.bizPostAddrMobileNo = bizPostAddrMobileNo;
	}

	@Column(name = "biz_post_addr_email", length = 50)
	public String getBizPostAddrEmail() {
		return this.bizPostAddrEmail;
	}

	public void setBizPostAddrEmail(String bizPostAddrEmail) {
		this.bizPostAddrEmail = bizPostAddrEmail;
	}

	@Column(name = "is_main_add_same_post_addr")
	public Boolean getIsMainAddSamePostAddr() {
		return isMainAddSamePostAddr;
	}

	public void setIsMainAddSamePostAddr(Boolean isMainAddSamePostAddr) {
		this.isMainAddSamePostAddr = isMainAddSamePostAddr;
	}

	@Column(name = "is_has_partnership_agreement")
	public Boolean getIsHasPartnershipAgreement() {
		return isHasPartnershipAgreement;
	}

	public void setIsHasPartnershipAgreement(Boolean isHasPartnershipAgreement) {
		this.isHasPartnershipAgreement = isHasPartnershipAgreement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	//@Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "robFormACode")
	@Transient
	public List<RobFormABranches> getListRobFormABranches() {
		return listRobFormABranches;
	}

	public void setListRobFormABranches(List<RobFormABranches> listRobFormABranches) {
		this.listRobFormABranches = listRobFormABranches;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "robFormACode")
	@Transient
	public List<RobFormABizCode> getListRobFormABizCode() {
		return listRobFormABizCode;
	}

	public void setListRobFormABizCode(List<RobFormABizCode> listRobFormABizCode) {
		this.listRobFormABizCode = listRobFormABizCode;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "robFormACode")
	@Transient
	public List<RobFormAOwner> getListRobFormAOwner() {
		return listRobFormAOwner;
	}

	public void setListRobFormAOwner(List<RobFormAOwner> listRobFormAOwner) {
		this.listRobFormAOwner = listRobFormAOwner;
	}

	@Transient
	public String getNewIcNoForOwners() {
		return newIcNoForOwners;
	}

	public void setNewIcNoForOwners(String newIcNoForOwners) {
		this.newIcNoForOwners = newIcNoForOwners;
	}

	@Transient
	public Boolean getDeclarationChkBox() {
		return declarationChkBox;
	}

	public void setDeclarationChkBox(Boolean declarationChkBox) {
		this.declarationChkBox = declarationChkBox;
	}

	public void copyFrom(RobFormA robFormAForm) {
		this.nameType = robFormAForm.getNameType();
		this.bizName= robFormAForm.getBizName();
		this.bizDesc= robFormAForm.getBizDesc();
		this.bizStartDt= robFormAForm.getBizStartDt();
		this.bizRegPeriod= robFormAForm.getBizRegPeriod();
		this.isHasPartnershipAgreement = robFormAForm.getIsHasPartnershipAgreement();	
		this.bizPartnershipAgreementDate= robFormAForm.getBizPartnershipAgreementDate();
		this.bizMainAddr= robFormAForm.getBizMainAddr();
		this.bizMainAddr2= robFormAForm.getBizMainAddr2();
		this.bizMainAddr3= robFormAForm.getBizMainAddr3();
		this.bizMainAddrTown= robFormAForm.getBizMainAddrTown();
		this.bizMainAddrPostcode= robFormAForm.getBizMainAddrPostcode();
		this.bizMainAddrState= robFormAForm.getBizMainAddrState();
		this.bizMainAddrTelNo= robFormAForm.getBizMainAddrTelNo();
		this.bizMainAddrMobileNo= robFormAForm.getBizMainAddrMobileNo();
		this.bizMainAddrEmail= robFormAForm.getBizMainAddrEmail();
		this.isMainAddSamePostAddr= robFormAForm.getIsMainAddSamePostAddr();	
		this.bizPostAddr= robFormAForm.getBizPostAddr();
		this.bizPostAddr2= robFormAForm.getBizPostAddr2();
		this.bizPostAddr3= robFormAForm.getBizPostAddr3();
		this.bizPostAddrTown= robFormAForm.getBizPostAddrTown();
		this.bizPostAddrState= robFormAForm.getBizPostAddrState();
		this.bizPostAddrPostcode= robFormAForm.getBizPostAddrPostcode();
		this.bizPostAddrTelNo= robFormAForm.getBizPostAddrTelNo();
		this.bizPostAddrMobileNo= robFormAForm.getBizPostAddrMobileNo();
		this.bizPostAddrEmail= robFormAForm.getBizPostAddrEmail();
		this.queryAnswer= robFormAForm.getQueryAnswer();
		this.isBuyInfo = robFormAForm.isBuyInfo();
		this.isIncubator = robFormAForm.isIncubator();
		this.isOnlineSeller = robFormAForm.getIsOnlineSeller();
		this.incentive = robFormAForm.getIncentive();
		this.bizMainAddrUrl=robFormAForm.getBizMainAddrUrl();
	}

	@Column(name = "status", nullable = false, length = 50)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "registration_amt", precision = 16, scale=2)
	public double getRegistrationAmt() {
		return registrationAmt;
	}

	public void setRegistrationAmt(double registrationAmt) {
		this.registrationAmt = registrationAmt;
	}

	@Column(name = "branches_amt", precision = 16, scale=2)
	public double getBranchesAmt() {
		return branchesAmt;
	}

	public void setBranchesAmt(double branchesAmt) {
		this.branchesAmt = branchesAmt;
	}
	
	@Column(name = "business_info_amt", precision = 16, scale=2)
	public double getBusinessInfoAmt() {
		return businessInfoAmt;
	}

	public void setBusinessInfoAmt(double businessInfoAmt) {
		this.businessInfoAmt = businessInfoAmt;
	}

	@Column(name = "total_amt", precision = 16, scale=2)
	public double getTotalAmt() {
		return totalAmt;
	}

	public void setTotalAmt(double totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "br_no", length = 20)
	public String getBrNo() {
		return brNo;
	}
	
	public void setBrNo(String brNo) {
		this.brNo = brNo;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="cert_file_data_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public LlpFileData getCertFileData() {
		return certFileData;
	}

	public void setCertFileData(LlpFileData certFileData) {
		this.certFileData = certFileData;
	}

	@Column(name = "biz_main_addr2", length = 70)
	public String getBizMainAddr2() {
		return bizMainAddr2;
	}

	public void setBizMainAddr2(String bizMainAddr2) {
		this.bizMainAddr2 = bizMainAddr2;
	}

	@Column(name = "biz_main_addr3", length = 70)
	public String getBizMainAddr3() {
		return bizMainAddr3;
	}

	public void setBizMainAddr3(String bizMainAddr3) {
		this.bizMainAddr3 = bizMainAddr3;
	}

	@Column(name = "biz_post_addr2", length = 70)
	public String getBizPostAddr2() {
		return bizPostAddr2;
	}

	public void setBizPostAddr2(String bizPostAddr2) {
		this.bizPostAddr2 = bizPostAddr2;
	}

	@Column(name = "biz_post_addr3", length = 70)
	public String getBizPostAddr3() {
		return bizPostAddr3;
	}

	public void setBizPostAddr3(String bizPostAddr3) {
		this.bizPostAddr3 = bizPostAddr3;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "robFormCode")
	@OrderBy("robFormNoteId ASC")
	public List<RobFormNotes> getListRobFormNotes() {
		return listRobFormNotes;
	}

	public void setListRobFormNotes(List<RobFormNotes> listRobFormNotes) {
		this.listRobFormNotes = listRobFormNotes;
	}

	@Transient
	public String getQueryAnswer() {
		return queryAnswer;
	}

	public void setQueryAnswer(String queryAnswer) {
		this.queryAnswer = queryAnswer;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="business_info_data_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public LlpFileData getBusinessInfoData() {
		return businessInfoData;
	}

	public void setBusinessInfoData(LlpFileData businessInfoData) {
		this.businessInfoData = businessInfoData;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="form_a_data_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public LlpFileData getFormAData() {
		return formAData;
	}

	public void setFormAData(LlpFileData formAData) {
		this.formAData = formAData;
	}

	@Column(name = "is_buy_info", length=1)
	public String isBuyInfo() {
		return isBuyInfo;
	}

	public void setBuyInfo(String isBuyInfo) {
		this.isBuyInfo = isBuyInfo;
	}

	@Column(name = "gst_amt", precision = 16, scale=2)
	public double getGstAmt() {
		return gstAmt;
	}

	public void setGstAmt(double gstAmt) {
		this.gstAmt = gstAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submit_dt", nullable = true, length = 3594)
	public Date getSubmitDt() {
		return submitDt;
	}

	public void setSubmitDt(Date submitDt) {
		this.submitDt = submitDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "resubmit_dt", nullable = true, length = 3594)
	public Date getReSubmitDt() {
		return reSubmitDt;
	}

	public void setReSubmitDt(Date reSubmitDt) {
		this.reSubmitDt = reSubmitDt;
	}
	
	@Column(name = "is_incubator", length=1)
	public String isIncubator() {
		return isIncubator;
	}

	public void setIncubator(String isIncubator) {
		this.isIncubator = isIncubator;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_dt", nullable = true, length = 3594)
	public Date getPaymentDt() {
		return paymentDt;
	}

	public void setPaymentDt(Date paymentDt) {
		this.paymentDt = paymentDt;
	}

	@Transient
	public String getPartnerShipAggStr() {
		if(isHasPartnershipAgreement){
			return com.ssm.llp.base.common.Parameter.YES_NO_yes;
		}else{
			return com.ssm.llp.base.common.Parameter.YES_NO_no;
		}
	}

	@Transient
	public List<FileUpload> getformAfileUpload() {
		return formAfileUpload;
	}

	public void setFileUploadTmp(List<FileUpload> formAfileUpload) {
		this.formAfileUpload = formAfileUpload;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="supporting_doc_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public LlpFileData getSupportingDocData() {
		return supportingDocData;
	}

	public void setSupportingDocData(LlpFileData supportingDocData) {
		this.supportingDocData = supportingDocData;
	}

	@Column(name = "is_has_supporting_doc", length = 1)
	public String getIsHasSupportingDoc() {
		return isHasSupportingDoc;
	}

	public void setIsHasSupportingDoc(String isHasSupportingDoc) {
		this.isHasSupportingDoc = isHasSupportingDoc;
	}

	@Column(name = "compound_no", length = 20)
	public String getCompoundNo() {
		return compoundNo;
	}

	public void setCompoundNo(String compoundNo) {
		this.compoundNo = compoundNo;
	}
	
	@OneToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="cmp_notice_file_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	public LlpFileData getCmpNoticeFileData() {
		return cmpNoticeFileData;
	}

	public void setCmpNoticeFileData(LlpFileData cmpNoticeFileData) {
		this.cmpNoticeFileData = cmpNoticeFileData;
	}
	
	@Column(name = "is_online_seller")
	public String getIsOnlineSeller() {
		return isOnlineSeller;
	}

	public void setIsOnlineSeller(String isOnlineSeller) {
		this.isOnlineSeller = isOnlineSeller;
	}

	@Column(name = "incentive")
	public String getIncentive() {
		return incentive;
	}

	public void setIncentive(String incentive) {
		this.incentive = incentive;
	}

	@Column(name = "approve_reject_notes")
	public String getApproveRejectNotes() {
		return approveRejectNotes;
	}

	public void setApproveRejectNotes(String approveRejectNotes) {
		this.approveRejectNotes = approveRejectNotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approve_reject_dt")
	public Date getApproveRejectDt() {
		return approveRejectDt;
	}

	public void setApproveRejectDt(Date approveRejectDt) {
		this.approveRejectDt = approveRejectDt;
	}
	
	@Column(name = "prosessing_branch", length = 5)
	public String getProsessingBranch() {
		return prosessingBranch;
	}

	public void setProsessingBranch(String prosessingBranch) {
		this.prosessingBranch = prosessingBranch;
	}

	
	@Version
	@Column(name = "row_version")
	public long getRowVersion() {
		return rowVersion;
	}

	public void setRowVersion(long rowVersion) {
		this.rowVersion = rowVersion;
	}
	
	@Column(name = "approve_reject_branch")
	public String getApproveRejectBranch() {
		return approveRejectBranch;
	}

	public void setApproveRejectBranch(String approveRejectBranch) {
		this.approveRejectBranch = approveRejectBranch;
	}

	@Column(name = "approve_reject_by")
	public String getApproveRejectBy() {
		return approveRejectBy;
	}

	public void setApproveRejectBy(String approveRejectBy) {
		this.approveRejectBy = approveRejectBy;
	}
	
	@Column(name = "is_from_ssm_pc") 
	public String getIsFromSSMPc() {
		return isFromSSMPc;
	}

	public void setIsFromSSMPc(String isFromSSMPc) {
		this.isFromSSMPc = isFromSSMPc;
	}

	@Column(name = "biz_main_addr_url") 
	public String getBizMainAddrUrl() {
		return bizMainAddrUrl;
	}

	public void setBizMainAddrUrl(String bizMainAddrUrl) {
		this.bizMainAddrUrl = bizMainAddrUrl;
	}
}
