package com.ssm.llp.base.common.model;

// Generated Dec 10, 2012 3:41:35 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

import com.ssm.llp.mod1.model.LlpUserProfile;

/**
 * LlpPaymentFee generated by hbm2java
 */
@Entity
@Table(name = "rob_payment_fee")
@Audited
public class LlpPaymentFee implements java.io.Serializable {

	private String paymentCode;
	private double paymentFee;
	private String status;
	private String gstCode;

	public LlpPaymentFee() {
	}

	public LlpPaymentFee(String paymentCode, String status) {
		this.paymentCode = paymentCode;
		this.status = status;
	}

	public LlpPaymentFee(String paymentCode, double paymentFee, String status) {
		this.paymentCode = paymentCode;
		this.paymentFee = paymentFee;
		this.status = status;
	}

	@Id
	@Column(name = "payment_code", unique = true, nullable = false, length = 25)
	public String getPaymentCode() {
		return this.paymentCode;
	}

	public void setPaymentCode(String paymentCode) {
		this.paymentCode = paymentCode;
	}

	@Column(name = "payment_fee", precision = 16, scale=2)
	public double getPaymentFee() {
		return this.paymentFee;
	}

	public void setPaymentFee(double paymentFee) {
		this.paymentFee = paymentFee;
	}

	@Column(name = "status", nullable = false, length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "gst_code", length = 2)
	public String getGstCode() {
		return gstCode;
	}

	public void setGstCode(String gstCode) {
		this.gstCode = gstCode;
	}
	


}
