package com.ssm.llp.ezbiz.model;

// Generated Aug 15, 2016 4:52:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.envers.Audited;

/**
 * CmpTransaction generated by hbm2java
 */
@Entity
@Audited
@Table(name = "cmp_transaction")
public class CmpTransaction implements java.io.Serializable {

	private String cmpTransactionCode;
	private String status;
	private double totalAmt;
	private Date paymentDt;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;

	public CmpTransaction() {
	}

	public CmpTransaction(String cmpTransactionCode, Date paymentDt, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.cmpTransactionCode = cmpTransactionCode;
		this.paymentDt = paymentDt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public CmpTransaction(String cmpTransactionCode, String status, double totalAmt, Date paymentDt, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.cmpTransactionCode = cmpTransactionCode;
		this.status = status;
		this.totalAmt = totalAmt;
		this.paymentDt = paymentDt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@GenericGenerator(name="ref_no", strategy="com.ssm.llp.base.hibernate.LlpIdGenerator", 
    parameters={@Parameter(name = "genCode", value = "CMP_RUNNING_NO"),
    			@Parameter(name = "fieldCode", value = "EB"),
    			@Parameter(name = "moduleCode", value = "-CMP"),
    			@Parameter(name = "yearMonthDay", value = "yyyyMMdd"),
    			@Parameter(name = "lastNoPattern", value = "00000")})
    @GeneratedValue(generator="ref_no")
	@Column(name = "cmp_transaction_code", unique = true, nullable = false, length = 25)
	public String getCmpTransactionCode() {
		return this.cmpTransactionCode;
	}

	public void setCmpTransactionCode(String cmpTransactionCode) {
		this.cmpTransactionCode = cmpTransactionCode;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "total_amt", precision = 16)
	public double getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(double totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "payment_dt", length = 3594)
	public Date getPaymentDt() {
		return this.paymentDt;
	}

	public void setPaymentDt(Date paymentDt) {
		this.paymentDt = paymentDt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

}
