package com.ssm.llp.base.common.model;

// Generated Jan 3, 2013 9:52:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LlpEmailLog generated by hbm2java
 */
@Entity
@Table(name = "rob_email_log")
public class LlpEmailLog implements java.io.Serializable {

	private long emailId;
	private String emailFrom;
	private String emailTo;
	private String emailSubject;
	private String emailBody;
	private Date sendDate;
	private String refNo;
	private String status;
	private String remark;
	private String bccList;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private Date eventDtFrom;
	private Date eventDtTo;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public LlpEmailLog() {
	}

	public LlpEmailLog(long emailId, String emailFrom) {
		this.emailId = emailId;
		this.emailFrom = emailFrom;
	}

	public LlpEmailLog(long emailId, String emailFrom, String emailTo, String emailSubject, String emailBody, Date sendDate, String refNo,
			String status, String remark) {
		this.emailId = emailId;
		this.emailFrom = emailFrom;
		this.emailTo = emailTo;
		this.emailSubject = emailSubject;
		this.emailBody = emailBody;
		this.sendDate = sendDate;
		this.refNo = refNo;
		this.status = status;
		this.remark = remark;
	}

	@Id
	@Column(name = "email_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getEmailId() {
		return this.emailId;
	}

	public void setEmailId(long emailId) {
		this.emailId = emailId;
	}

	@Column(name = "email_from", nullable = false)
	public String getEmailFrom() {
		return this.emailFrom;
	}

	public void setEmailFrom(String emailFrom) {
		this.emailFrom = emailFrom;
	}

	@Column(name = "email_to")
	public String getEmailTo() {
		return this.emailTo;
	}

	public void setEmailTo(String emailTo) {
		this.emailTo = emailTo;
	}

	@Column(name = "email_subject", length = 56)
	public String getEmailSubject() {
		return this.emailSubject;
	}

	public void setEmailSubject(String emailSubject) {
		this.emailSubject = emailSubject;
	}

	@Column(name = "email_body", length = 56)
	public String getEmailBody() {
		return this.emailBody;
	}

	public void setEmailBody(String emailBody) {
		this.emailBody = emailBody;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_date", length = 3594)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	@Column(name = "ref_no", length = 50)
	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "remark", length = 56)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "bcc_list")
	public String getBccList() {
		return bccList;
	}

	public void setBccList(String bccList) {
		this.bccList = bccList;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "event_dt_from", length = 3594)
	public Date getEventDtFrom() {
		return eventDtFrom;
	}

	public void setEventDtFrom(Date eventDtFrom) {
		this.eventDtFrom = eventDtFrom;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "event_dt_to", length = 3594)
	public Date getEventDtTo() {
		return eventDtTo;
	}

	public void setEventDtTo(Date eventDtTo) {
		this.eventDtTo = eventDtTo;
	}

}
