package com.ssm.llp.base.common.model;

// Generated Dec 5, 2012 9:08:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LlpRunningNo generated by hbm2java
 */
@Entity
@Table(name = "rob_running_no", uniqueConstraints = @UniqueConstraint(columnNames = {
		"module_code", "field_code", "year_month_day" }))
public class LlpRunningNo implements java.io.Serializable {

	private long runningNoId;
	private String genCode;
	private String fieldCode;
	private String moduleCode;
	private String yearMonthDay;
	private String lastNo;

	public LlpRunningNo() {
	}

	public LlpRunningNo(long runningNoId) {
		this.runningNoId = runningNoId;
	}

	public LlpRunningNo(long runningNoId, String fieldCode, String moduleCode,
			String yearMonthDay, String lastNo) {
		this.runningNoId = runningNoId;
		this.fieldCode = fieldCode;
		this.moduleCode = moduleCode;
		this.yearMonthDay = yearMonthDay;
		this.lastNo = lastNo;
	}

	@Id
	@Column(name = "running_no_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRunningNoId() {
		return this.runningNoId;
	}

	public void setRunningNoId(long runningNoId) {
		this.runningNoId = runningNoId;
	}

	@Column(name = "field_code", length = 10)
	public String getFieldCode() {
		return this.fieldCode;
	}

	public void setFieldCode(String fieldCode) {
		this.fieldCode = fieldCode;
	}

	@Column(name = "module_code", length = 10)
	public String getModuleCode() {
		return this.moduleCode;
	}

	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	@Column(name = "year_month_day", length = 10)
	public String getYearMonthDay() {
		return this.yearMonthDay;
	}

	public void setYearMonthDay(String yearMonthDay) {
		this.yearMonthDay = yearMonthDay;
	}

	@Column(name = "last_no", length = 10)
	public String getLastNo() {
		return this.lastNo;
	}

	public void setLastNo(String lastNo) {
		this.lastNo = lastNo;
	}

	@Column(name = "gen_code", length = 50)
	public String getGenCode() {
		return genCode;
	}

	public void setGenCode(String genCode) {
		this.genCode = genCode;
	}

}
