package com.ssm.llp.mod1.model;

// Generated Dec 7, 2012 3:54:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

import com.ssm.llp.ezbiz.model.RocBlacklist;
import com.ssm.llp.ezbiz.model.RocBusinessObjectCode;

/**
 * LlpBusinessCodeLink generated by hbm2java
 */
@Entity
@Table(name = "rob_business_code_link")
@Audited
public class LlpBusinessCodeLink implements java.io.Serializable {

	private long idBusinessCodeLink;
	private String businessCode;
	private String llpNo;
	private String status;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private RocBusinessObjectCode rocBusinessObjectCode;

	public LlpBusinessCodeLink() {
	}

	public LlpBusinessCodeLink(long idBusinessCodeLink, String businessCode,
			String llpNo, String status, Date createDt, String createBy,
			Date updateDt, String updateBy) {
		this.idBusinessCodeLink = idBusinessCodeLink;
		this.businessCode = businessCode;
		this.llpNo = llpNo;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "id_business_code_link", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getIdBusinessCodeLink() {
		return this.idBusinessCodeLink;
	}

	public void setIdBusinessCodeLink(long idBusinessCodeLink) {
		this.idBusinessCodeLink = idBusinessCodeLink;
	}

	@Column(name = "business_code", nullable = false, length = 10)
	public String getBusinessCode() {
		return this.businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}

	@Column(name = "llp_no", nullable = false, length = 30)
	public String getLlpNo() {
		return this.llpNo;
	}

	public void setLlpNo(String llpNo) {
		this.llpNo = llpNo;
	}

	@Column(name = "status", nullable = false, length = 4)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

//	@ManyToOne(fetch = FetchType.EAGER)
//	@JoinColumn(name = "vchbusinesscode", nullable = false, insertable = false, updatable = false)
	@Transient
	public RocBusinessObjectCode getRocBusinessObjectCode() {
		return rocBusinessObjectCode;
	}

	public void setRocBusinessObjectCode(RocBusinessObjectCode rocBusinessObjectCode) {
		this.rocBusinessObjectCode = rocBusinessObjectCode;
	}
	
}
