package com.ssm.llp.mod1.model;

// Generated Nov 30, 2012 9:49:47 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

/**
 * LlpPartnerLink generated by hbm2java
 */
@Entity
@Table(name = "rob_partner_link")
@Audited
public class LlpPartnerLink implements java.io.Serializable {

	private long idPartnerLink;
	private String llpNo;
	private String userRefNo;
	private String linkStatus;
	private String type;
	private String capitalContribution;
	private String add1;
	private String add2;
	private String add3;
	private String country = com.ssm.llp.base.common.Parameter.COUNTRY_CODE_malaysia;
	private String state;
	private String city;
	private String postcode;
	private String hpNo;
	private String offNo;
	private String faxNo;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private String email;
	private Date appointmentDate;
	private Date resignDate;
	
	private LlpUserProfile llpUserProfile;

	public LlpPartnerLink() {
	}

	public LlpPartnerLink(long idPartnerLink, Date createDt, String createBy,
			Date updateDt, String updateBy) {
		this.idPartnerLink = idPartnerLink;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpPartnerLink(long idPartnerLink, String llpNo, String userRefNo,
			String linkStatus, String type, String capitalContribution,
			String add1, String add2, String add3, String country,
			String state, String city, String postcode, String hpNo,
			String offNo, String faxNo, Date createDt, String createBy,
			Date updateDt, String updateBy, String email, Date appointmentDate, Date resignDate) {
		this.idPartnerLink = idPartnerLink;
		this.llpNo = llpNo;
		this.userRefNo = userRefNo;
		this.linkStatus = linkStatus;
		this.type = type;
		this.capitalContribution = capitalContribution;
		this.add1 = add1;
		this.add2 = add2;
		this.add3 = add3;
		this.country = country;
		this.state = state;
		this.city = city;
		this.postcode = postcode;
		this.hpNo = hpNo;
		this.offNo = offNo;
		this.faxNo = faxNo;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.email = email;
		this.appointmentDate = appointmentDate;
		this.resignDate = resignDate;
	}
	
	
	@Id
	@Column(name = "id_partner_link", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getIdPartnerLink() {
		return this.idPartnerLink;
	}

	public void setIdPartnerLink(long idPartnerLink) {
		this.idPartnerLink = idPartnerLink;
	}

	@Column(name = "llp_no", length = 25)
	public String getLlpNo() {
		return this.llpNo;
	}

	public void setLlpNo(String llpNo) {
		this.llpNo = llpNo;
	}
	@Column(name = "link_status", length = 4)
	public String getLinkStatus() {
		return this.linkStatus;
	}

	public void setLinkStatus(String linkStatus) {
		this.linkStatus = linkStatus;
	}

	@Column(name = "type", length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "capital_contribution", length = 20)
	public String getCapitalContribution() {
		return this.capitalContribution;
	}

	public void setCapitalContribution(String capitalContribution) {
		this.capitalContribution = capitalContribution;
	}

	@Column(name = "add1", length = 150)
	public String getAdd1() {
		return this.add1;
	}

	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	@Column(name = "add2", length = 150)
	public String getAdd2() {
		return this.add2;
	}

	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	@Column(name = "add3", length = 150)
	public String getAdd3() {
		return this.add3;
	}

	public void setAdd3(String add3) {
		this.add3 = add3;
	}

	@Column(name = "country", length = 4)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state", length = 4)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city", length = 150)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postcode", length = 10)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "hp_no", length = 15)
	public String getHpNo() {
		return this.hpNo;
	}

	public void setHpNo(String hpNo) {
		this.hpNo = hpNo;
	}

	@Column(name = "off_no", length = 15)
	public String getOffNo() {
		return this.offNo;
	}

	public void setOffNo(String offNo) {
		this.offNo = offNo;
	}

	@Column(name = "fax_no", length = 15)
	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	//@Column(name = "id_reg_user", nullable = false, length = 25)
	@Column(name = "user_ref_no", nullable = false, length = 25)
	public String getUserRefNo() {
		return userRefNo;
	}

	public void setUserRefNo(String userRefNo) {
		this.userRefNo = userRefNo;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Transient
	public void copyDataFromProfile(LlpUserProfile llpUserProfile) { //use in llpRegistrationBasePage, partner
		setAdd1(llpUserProfile.getAdd1());
    	setAdd2(llpUserProfile.getAdd2());
    	setAdd3(llpUserProfile.getAdd3());
    	setPostcode(llpUserProfile.getPostcode());
    	setCity(llpUserProfile.getCity());
    	setState(llpUserProfile.getState());
    	setCountry(llpUserProfile.getCountry());
    	setEmail(llpUserProfile.getEmail());
    	setOffNo(llpUserProfile.getOffNo());
    	setHpNo(llpUserProfile.getHpNo());
    	setFaxNo(llpUserProfile.getFaxNo());
 
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_ref_no", nullable = false, insertable = false, updatable = false)
	public LlpUserProfile getLlpUserProfile() {
		return llpUserProfile;
	}

	public void setLlpUserProfile(LlpUserProfile llpUserProfile) {
		this.llpUserProfile = llpUserProfile;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appointment_date", length = 3594)
	public Date getAppointmentDate() {
		return appointmentDate;
	}

	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "resign_date", length = 3594)
	public Date getResignDate() {
		return resignDate;
	}

	public void setResignDate(Date resignDate) {
		this.resignDate = resignDate;
	}
	
	

}
