package com.ssm.llp.mod1.model;

// Generated Nov 30, 2012 9:49:47 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.envers.Audited;

/**
 * LlpRegistration generated by hbm2java
 */
@Entity
@Table(name = "rob_registration")
@Audited
public class LlpRegistration implements java.io.Serializable {

	private long idLlp;
	private String llpNo;
	private Date regDate;
	private String llpName;
	private String regAdd1;
	private String regAdd2;
	private String regAdd3;
	private String regCountry = com.ssm.llp.base.common.Parameter.COUNTRY_CODE_malaysia; //onload default Malaysia
	private String regState;
	private String regCity;
	private String regPostcode;
	private String bussinessAdd1;
	private String bussinessAdd2;
	private String bussinessAdd3;
	private String bussinessCountryCode = com.ssm.llp.base.common.Parameter.COUNTRY_CODE_malaysia;
	private String bussinessStateCode;
	private String bussinessCity;
	private String bussinessPostcode;
	private String natureOfBusinessDesc;
	private String llpStatus;
	private String offTelNo;
	private String hpNo;
	private String faxNo;
	private String capitalContribution;
	private String agreementLlp = com.ssm.llp.base.common.Parameter.YES_NO_no;
	private String regType;
	private String email;
	private Date terminationDate;
	private String foreignCountry;  
	private String profBodyType; //ca, law, cs
	private String profBodyCode; //maicsa, mia etc
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private String internalRemark;
	private String lodgeBy;
	private Date agreementLlpDate;
	private String noOfPartner;
	private Boolean declareChk = Boolean.FALSE;	
	private String profFirmName;
	private String profFirmNo;
	private String profInsuranceCompany;
	private String profInsuranceTotalAmt;
	private Date profInsurancePolicyFrom;
	private Date profInsurancePolicyTo;
	
	//to combine LlpRregistration with NS
	private LlpReservedName llpReservedName;
	
	//to combine LlpRregistration with CO, partner and lodger info.
	private List<LlpPartnerLink> llpPartnerLinks = new ArrayList<LlpPartnerLink>(0);
	
	//to combine LlpRregistration with businessObject : to-do
	private List<LlpBusinessCodeLink> llpBusinessCodeLink = new ArrayList<LlpBusinessCodeLink>(0);

	public LlpRegistration() {
	}

	public LlpRegistration(long idLlp, String llpNo, Date regDate,
			String llpName, String regAdd1, String regCountry, String regState,
			String regCity, String regPostcode, Date terminationDate,
			Date createDt, String createBy, Date updateDt, String updateBy) {
		this.idLlp = idLlp;
		this.llpNo = llpNo;
		this.regDate = regDate;
		this.llpName = llpName;
		this.regAdd1 = regAdd1;
		this.regCountry = regCountry;
		this.regState = regState;
		this.regCity = regCity;
		this.regPostcode = regPostcode;
		this.terminationDate = terminationDate;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpRegistration(long idLlp, String llpNo, Date regDate,
			String llpName, String regAdd1, String regAdd2, String regAdd3,
			String regCountry, String regState, String regCity,
			String regPostcode, String bussinessAdd1, String bussinessAdd2,
			String bussinessAdd3, String bussinessCountryCode,
			String bussinessStateCode, String bussinessCity,
			String bussinessPostcode, String natureOfBusinessDesc,
			String llpStatus, String offTelNo, String hpNo, String faxNo,
			String capitalContribution, String agreementLlp, String regType,
			String email, Date terminationDate, String foreignCountry,
			Date createDt, String createBy, Date updateDt, String updateBy, String internalRemark, String lodgeBy, Date agreementLlpDate, String noOfPartner,
			String profFirmName, String profFirmNo, String profInsuranceCompany, String profInsuranceTotalAmt, 
			Date profInsurancePolicyFrom, Date profInsurancePolicyTo) {
		this.idLlp = idLlp;
		this.llpNo = llpNo;
		this.regDate = regDate;
		this.llpName = llpName;
		this.regAdd1 = regAdd1;
		this.regAdd2 = regAdd2;
		this.regAdd3 = regAdd3;
		this.regCountry = regCountry;
		this.regState = regState;
		this.regCity = regCity;
		this.regPostcode = regPostcode;
		this.bussinessAdd1 = bussinessAdd1;
		this.bussinessAdd2 = bussinessAdd2;
		this.bussinessAdd3 = bussinessAdd3;
		this.bussinessCountryCode = bussinessCountryCode;
		this.bussinessStateCode = bussinessStateCode;
		this.bussinessCity = bussinessCity;
		this.bussinessPostcode = bussinessPostcode;
		this.natureOfBusinessDesc = natureOfBusinessDesc;
		this.llpStatus = llpStatus;
		this.offTelNo = offTelNo;
		this.hpNo = hpNo;
		this.faxNo = faxNo;
		this.capitalContribution = capitalContribution;
		this.agreementLlp = agreementLlp;
		this.regType = regType;
		this.email = email;
		this.terminationDate = terminationDate;
		this.foreignCountry = foreignCountry;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
		this.internalRemark = internalRemark;
		this.lodgeBy = lodgeBy;
		this.agreementLlpDate = agreementLlpDate;
		this.noOfPartner = noOfPartner;
		this.profFirmName = profFirmName;
		this.profFirmNo = profFirmNo;
		this.profInsuranceCompany = profInsuranceCompany;
		this.profInsuranceTotalAmt = profInsuranceTotalAmt;
		this.profInsurancePolicyFrom = profInsurancePolicyFrom;
		this.profInsurancePolicyTo = profInsurancePolicyTo;
	}

	@Column(name = "id_llp", unique = true, nullable = false, updatable=false)
	public long getIdLlp() {
		return this.idLlp;
	}

	public void setIdLlp(long idLlp) {
		this.idLlp = idLlp;
	}

	//LlpReservedNameDaoImpl effected if we change this parameter
	@Id
	@GenericGenerator(name="llp_no", strategy="com.ssm.llp.base.hibernate.LlpIdGenerator", 
    parameters={@Parameter(name = "genCode", value = "LLP_REG_RUNNING_NO"),
				@Parameter(name = "fieldCode", value = "LLP"),
    			@Parameter(name = "lastNoPattern", value = "0000000")})
    @GeneratedValue(generator="llp_no")
	@Column(name = "llp_no", unique = true, nullable = false, length = 30)
	public String getLlpNo() {
		return this.llpNo;
	}

	public void setLlpNo(String llpNo) {
		this.llpNo = llpNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 3594)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "llp_name", nullable = false, length = 100)
	public String getLlpName() {
		return this.llpName;
	}

	public void setLlpName(String llpName) {
		this.llpName = llpName;
	}

	@Column(name = "reg_add1", nullable = false, length = 150)
	public String getRegAdd1() {
		return this.regAdd1;
	}

	public void setRegAdd1(String regAdd1) {
		this.regAdd1 = regAdd1;
	}

	@Column(name = "reg_add2", length = 150)
	public String getRegAdd2() {
		return this.regAdd2;
	}

	public void setRegAdd2(String regAdd2) {
		this.regAdd2 = regAdd2;
	}

	@Column(name = "reg_add3", length = 150)
	public String getRegAdd3() {
		return this.regAdd3;
	}

	public void setRegAdd3(String regAdd3) {
		this.regAdd3 = regAdd3;
	}

	@Column(name = "reg_country", nullable = false, length = 4)
	public String getRegCountry() {
		return this.regCountry;
	}

	public void setRegCountry(String regCountry) {
		this.regCountry = regCountry;
	}

	@Column(name = "reg_state", length = 4)
	public String getRegState() {
		return this.regState;
	}

	public void setRegState(String regState) {
		this.regState = regState;
	}

	@Column(name = "reg_city", nullable = false, length = 150)
	public String getRegCity() {
		return this.regCity;
	}

	public void setRegCity(String regCity) {
		this.regCity = regCity;
	}

	@Column(name = "reg_postcode", nullable = false, length = 10)
	public String getRegPostcode() {
		return this.regPostcode;
	}

	public void setRegPostcode(String regPostcode) {
		this.regPostcode = regPostcode;
	}

	@Column(name = "bussiness_add1", length = 150)
	public String getBussinessAdd1() {
		return this.bussinessAdd1;
	}

	public void setBussinessAdd1(String bussinessAdd1) {
		this.bussinessAdd1 = bussinessAdd1;
	}

	@Column(name = "bussiness_add2", length = 150)
	public String getBussinessAdd2() {
		return this.bussinessAdd2;
	}

	public void setBussinessAdd2(String bussinessAdd2) {
		this.bussinessAdd2 = bussinessAdd2;
	}

	@Column(name = "bussiness_add3", length = 150)
	public String getBussinessAdd3() {
		return this.bussinessAdd3;
	}

	public void setBussinessAdd3(String bussinessAdd3) {
		this.bussinessAdd3 = bussinessAdd3;
	}

	@Column(name = "bussiness_country_code", length = 4)
	public String getBussinessCountryCode() {
		return this.bussinessCountryCode;
	}

	public void setBussinessCountryCode(String bussinessCountryCode) {
		this.bussinessCountryCode = bussinessCountryCode;
	}

	@Column(name = "bussiness_state_code", length = 4)
	public String getBussinessStateCode() {
		return this.bussinessStateCode;
	}

	public void setBussinessStateCode(String bussinessStateCode) {
		this.bussinessStateCode = bussinessStateCode;
	}

	@Column(name = "bussiness_city", length = 150)
	public String getBussinessCity() {
		return this.bussinessCity;
	}

	public void setBussinessCity(String bussinessCity) {
		this.bussinessCity = bussinessCity;
	}

	@Column(name = "bussiness_postcode", length = 10)
	public String getBussinessPostcode() {
		return this.bussinessPostcode;
	}

	public void setBussinessPostcode(String bussinessPostcode) {
		this.bussinessPostcode = bussinessPostcode;
	}

	@Column(name = "nature_of_business_desc", length = 600)
	public String getNatureOfBusinessDesc() {
		return this.natureOfBusinessDesc;
	}

	public void setNatureOfBusinessDesc(String natureOfBusinessDesc) {
		this.natureOfBusinessDesc = natureOfBusinessDesc;
	}

	@Column(name = "llp_status", length = 4)
	public String getLlpStatus() {
		return this.llpStatus;
	}

	public void setLlpStatus(String llpStatus) {
		this.llpStatus = llpStatus;
	}

	@Column(name = "off_tel_no", length = 15)
	public String getOffTelNo() {
		return this.offTelNo;
	}

	public void setOffTelNo(String offTelNo) {
		this.offTelNo = offTelNo;
	}

	@Column(name = "hp_no", length = 15)
	public String getHpNo() {
		return this.hpNo;
	}

	public void setHpNo(String hpNo) {
		this.hpNo = hpNo;
	}

	@Column(name = "fax_no", length = 15)
	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	@Column(name = "capital_contribution", length = 20)
	public String getCapitalContribution() {
		return this.capitalContribution;
	}

	public void setCapitalContribution(String capitalContribution) {
		this.capitalContribution = capitalContribution;
	}

	@Column(name = "agreement_llp", length = 4)
	public String getAgreementLlp() {
		return this.agreementLlp;
	}

	public void setAgreementLlp(String agreementLlp) {
		this.agreementLlp = agreementLlp;
	}

	@Column(name = "reg_type", length = 4)
	public String getRegType() {
		return this.regType;
	}

	public void setRegType(String regType) {
		this.regType = regType;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "termination_date", length = 3594)
	public Date getTerminationDate() {
		return this.terminationDate;
	}

	public void setTerminationDate(Date terminationDate) {
		this.terminationDate = terminationDate;
	}

	@Column(name = "foreign_country", length = 4)
	public String getForeignCountry() {
		return this.foreignCountry;
	}

	public void setForeignCountry(String foreignCountry) {
		this.foreignCountry = foreignCountry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "internal_remark", length = 600)
	public String getInternalRemark() {
		return internalRemark;
	}

	public void setInternalRemark(String internalRemark) {
		this.internalRemark = internalRemark;
	}
	
	@Column(name = "lodge_by", length = 50)
	public String getLodgeBy() {
		return lodgeBy;
	}

	public void setLodgeBy(String lodgeBy) {
		this.lodgeBy = lodgeBy;
	}

	@Transient
	public LlpReservedName getLlpReservedName() {
		return llpReservedName;
	}

	public void setLlpReservedName(LlpReservedName llpReservedName) {
		this.llpReservedName = llpReservedName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "llpNo")
	public List<LlpPartnerLink> getLlpPartnerLinks() {
		return llpPartnerLinks;
	}

	public void setLlpPartnerLinks(List<LlpPartnerLink> llpPartnerLinks) {
		this.llpPartnerLinks = llpPartnerLinks;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "llpNo")
	public List<LlpBusinessCodeLink> getLlpBusinessCodeLink() {
		return llpBusinessCodeLink;
	}

	public void setLlpBusinessCodeLink(List<LlpBusinessCodeLink> llpBusinessCodeLink) {
		this.llpBusinessCodeLink = llpBusinessCodeLink;
	}

	@Column(name = "prof_body_type", length = 4)
	public String getProfBodyType() {
		return profBodyType;
	}

	public void setProfBodyType(String profBodyType) {
		this.profBodyType = profBodyType;
	}

	@Column(name = "prof_body_code", length = 10)
	public String getProfBodyCode() {
		return profBodyCode;
	}

	public void setProfBodyCode(String profBodyCode) {
		this.profBodyCode = profBodyCode;
	}

	@Column(name = "no_of_partner", length = 15)
	public String getNoOfPartner() {
		return noOfPartner;
	}

	public void setNoOfPartner(String noOfPartner) {
		this.noOfPartner = noOfPartner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "agreement_llp_date", length = 3594)
	public Date getAgreementLlpDate() {
		return agreementLlpDate;
	}

	public void setAgreementLlpDate(Date agreementLlpDate) {
		this.agreementLlpDate = agreementLlpDate;
	}

	@Transient
	public Boolean getDeclareChk() {
		return declareChk;
	}

	public void setDeclareChk(Boolean declareChk) {
		this.declareChk = declareChk;
	}

	@Column(name = "prof_firm_name", length = 150)
	public String getProfFirmName() {
		return profFirmName;
	}

	public void setProfFirmName(String profFirmName) {
		this.profFirmName = profFirmName;
	}

	@Column(name = "prof_firm_no", length = 25)
	public String getProfFirmNo() {
		return profFirmNo;
	}

	public void setProfFirmNo(String profFirmNo) {
		this.profFirmNo = profFirmNo;
	}

	@Column(name = "prof_insurance_company", length = 150)
	public String getProfInsuranceCompany() {
		return profInsuranceCompany;
	}

	public void setProfInsuranceCompany(String profInsuranceCompany) {
		this.profInsuranceCompany = profInsuranceCompany;
	}

	@Column(name = "prof_insurance_total_amt", length = 25)
	public String getProfInsuranceTotalAmt() {
		return profInsuranceTotalAmt;
	}

	public void setProfInsuranceTotalAmt(String profInsuranceTotalAmt) {
		this.profInsuranceTotalAmt = profInsuranceTotalAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prof_insurance_policy_from", length = 3594)
	public Date getProfInsurancePolicyFrom() {
		return profInsurancePolicyFrom;
	}

	public void setProfInsurancePolicyFrom(Date profInsurancePolicyFrom) {
		this.profInsurancePolicyFrom = profInsurancePolicyFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "prof_insurance_policy_to", length = 3594)
	public Date getProfInsurancePolicyTo() {
		return profInsurancePolicyTo;
	}

	public void setProfInsurancePolicyTo(Date profInsurancePolicyTo) {
		this.profInsurancePolicyTo = profInsurancePolicyTo;
	}


}
