package com.ssm.llp.base.common.model;

// Generated Nov 30, 2012 8:17:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import com.ssm.llp.base.common.Parameter;

/**
 * LlpParameters generated by hbm2java
 */
@Entity
@Table(name = "rob_parameters")
@Audited
public class LlpParameters implements java.io.Serializable {

	private int idParameter;
	private String code;
	private String codeDesc;
	private String codeType;
	private String parentCodeType;
	private String parentCode;
	private String status;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private Integer seq;

	public LlpParameters() {
	}
	
	public LlpParameters(String code, String codeDesc) {
		this.code = code;
		this.codeDesc = codeDesc;
	}
	
	public LlpParameters(String code, String codeDesc, String codeType) {
		this.code = code;
		this.codeDesc = codeDesc;
		this.codeType = codeType;
		this.status = Parameter.PARAMETER_STATUS_active;
		seq = 0;
	}

	public LlpParameters(int idParameter, Date createDt, String createBy,
			Date updateDt, String updateBy) {
		this.idParameter = idParameter;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpParameters(int idParameter, String code, String codeDesc,
			String codeType, String parentCodeType, String parentCode,
			String status, Date createDt, String createBy, Date updateDt,
			String updateBy) {
		this.idParameter = idParameter;
		this.code = code;
		this.codeDesc = codeDesc;
		this.codeType = codeType;
		this.parentCodeType = parentCodeType;
		this.parentCode = parentCode;
		this.status = status;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "id_parameter", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getIdParameter() {
		return this.idParameter;
	}

	public void setIdParameter(int idParameter) {
		this.idParameter = idParameter;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "code_desc")
	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	@Column(name = "code_type")
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "parent_code_type")
	public String getParentCodeType() {
		return this.parentCodeType;
	}

	public void setParentCodeType(String parentCodeType) {
		this.parentCodeType = parentCodeType;
	}

	@Column(name = "parent_code")
	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	@Column(name = "status", length = 4)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	
	@Column(name = "seq")
	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}
	
	@Override
	public String toString() {
		return code;
	}
}
