package com.ssm.llp.base.common.model;

// Generated May 17, 2013 9:58:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LlpSupplyInfoHdr generated by hbm2java
 */
@Entity
@Table(name = "rob_supply_info_hdr")
public class LlpSupplyInfoHdr implements java.io.Serializable {

	private String hdrCode;
	private String fileDesc;
	private Date expiredDt;
	private String hdrStatus;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	private double totalProfileAmt;
	private double totalCertAmt;
	private double totalAmt;

	public LlpSupplyInfoHdr() {
	}

	public LlpSupplyInfoHdr(String hdrCode, Date expiredDt, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.hdrCode = hdrCode;
		this.expiredDt = expiredDt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public LlpSupplyInfoHdr(String hdrCode, String llpNo, String llpName, String fileDesc, Date expiredDt, String hdrStatus,
			Date createDt, String createBy, Date updateDt, String updateBy) {
		this.hdrCode = hdrCode;
		this.fileDesc = fileDesc;
		this.expiredDt = expiredDt;
		this.hdrStatus = hdrStatus;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
    @GenericGenerator(name="ref_no", strategy="com.ssm.llp.base.hibernate.LlpIdGenerator", 
    parameters={@Parameter(name = "genCode", value = "LLP_SUPPLY_INFO_RUNNING_NO"),
    			@Parameter(name = "fieldCode", value = "LLPSP"),
    			@Parameter(name = "moduleCode", value = "05"),
    			@Parameter(name = "yearMonthDay", value = "yyyyMMdd"),
    			@Parameter(name = "lastNoPattern", value = "000000")})
    @GeneratedValue(generator="ref_no")
	@Column(name = "hdr_code", nullable = false, length = 50)
	public String getHdrCode() {
		return this.hdrCode;
	}

	public void setHdrCode(String hdrCode) {
		this.hdrCode = hdrCode;
	}


	@Column(name = "file_desc")
	public String getFileDesc() {
		return this.fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expired_dt", length = 3594)
	public Date getExpiredDt() {
		return this.expiredDt;
	}

	public void setExpiredDt(Date expiredDt) {
		this.expiredDt = expiredDt;
	}

	@Column(name = "hdr_status", length = 5)
	public String getHdrStatus() {
		return this.hdrStatus;
	}

	public void setHdrStatus(String hdrStatus) {
		this.hdrStatus = hdrStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Column(name = "total_profile_amt", nullable = false, precision = 16, scale=2)
	public double getTotalProfileAmt() {
		return totalProfileAmt;
	}

	public void setTotalProfileAmt(double totalProfileAmt) {
		this.totalProfileAmt = totalProfileAmt;
	}

	@Column(name = "total_cert_amt", nullable = false, precision = 16, scale=2)
	public double getTotalCertAmt() {
		return totalCertAmt;
	}

	public void setTotalCertAmt(double totalCertAmt) {
		this.totalCertAmt = totalCertAmt;
	}

	@Column(name = "total_amt", nullable = false, precision = 16, scale=2)
	public double getTotalAmt() {
		return totalAmt;
	}

	public void setTotalAmt(double totalAmt) {
		this.totalAmt = totalAmt;
	}
	
	

}
