package com.ssm.llp.ezbiz.model;

// Generated Jun 14, 2016 9:59:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;

/**
 * RobEBranchTransaction generated by hbm2java
 */
@Entity
@Table(name = "rob_ebranch_transaction")
@Audited
public class RobEBranchTransaction implements java.io.Serializable {

	private long robEBranchTransactionId;
	private Long robEbranchId;
	private String name;
	private String brNo;
	private String chkDigit;
	private String status;
	private Integer quantityAmt;
	private double branchesAmt;
	private double totalAmt;
	private double gstAmt;
	private Date createDt;
	private String createBy;
	private Date updateDt;
	private String updateBy;
	
	private List<RobEBranchTransactionDetail>  listRobEBranchTransactionDetail = new ArrayList<RobEBranchTransactionDetail>(0);

	public RobEBranchTransaction() {
	}

	public RobEBranchTransaction(long robEBranchTransactionId, Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robEBranchTransactionId = robEBranchTransactionId;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	public RobEBranchTransaction(long robEBranchTransactionId, Long robEbranchId, String name, String brNo, String chkDigit, String platform,
			String platformOthers, String url, String status, Integer quantityAmt, double branchesAmt, double totalAmt, double gstAmt,
			Date createDt, String createBy, Date updateDt, String updateBy) {
		this.robEBranchTransactionId = robEBranchTransactionId;
		this.robEbranchId = robEbranchId;
		this.name = name;
		this.brNo = brNo;
		this.chkDigit = chkDigit;
		this.status = status;
		this.quantityAmt = quantityAmt;
		this.branchesAmt = branchesAmt;
		this.totalAmt = totalAmt;
		this.gstAmt = gstAmt;
		this.createDt = createDt;
		this.createBy = createBy;
		this.updateDt = updateDt;
		this.updateBy = updateBy;
	}

	@Id
	@Column(name = "rob_ebranch_transaction_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRobEBranchTransactionId() {
		return robEBranchTransactionId;
	}

	public void setRobEBranchTransactionId(long robEBranchTransactionId) {
		this.robEBranchTransactionId = robEBranchTransactionId;
	}

	@Column(name = "rob_ebranch_id")
	public Long getRobEbranchId() {
		return this.robEbranchId;
	}

	public void setRobEbranchId(Long robEbranchId) {
		this.robEbranchId = robEbranchId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "br_no", length = 10)
	public String getBrNo() {
		return this.brNo;
	}

	public void setBrNo(String brNo) {
		this.brNo = brNo;
	}

	@Column(name = "chk_digit", length = 2)
	public String getChkDigit() {
		return this.chkDigit;
	}

	public void setChkDigit(String chkDigit) {
		this.chkDigit = chkDigit;
	}

	@Column(name = "status", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "quantity_amt")
	public Integer getQuantityAmt() {
		return this.quantityAmt;
	}

	public void setQuantityAmt(Integer quantityAmt) {
		this.quantityAmt = quantityAmt;
	}

	@Column(name = "branches_amt", precision = 16)
	public double getBranchesAmt() {
		return this.branchesAmt;
	}

	public void setBranchesAmt(double branchesAmt) {
		this.branchesAmt = branchesAmt;
	}

	@Column(name = "total_amt", precision = 16)
	public double getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(double totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "gst_amt", precision = 16)
	public double getGstAmt() {
		return this.gstAmt;
	}

	public void setGstAmt(double gstAmt) {
		this.gstAmt = gstAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_dt", nullable = false, length = 3594)
	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	@Column(name = "create_by", nullable = false, length = 50)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_dt", nullable = false, length = 3594)
	public Date getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Date updateDt) {
		this.updateDt = updateDt;
	}

	@Column(name = "update_by", nullable = false, length = 50)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Transient
	public List<RobEBranchTransactionDetail> getListRobEBranchTransactionDetail() {
		return listRobEBranchTransactionDetail;
	}

	public void setListRobEBranchTransactionDetail(List<RobEBranchTransactionDetail> listRobEBranchTransactionDetail) {
		this.listRobEBranchTransactionDetail = listRobEBranchTransactionDetail;
	}

}
