package com.ssm.llp.ezbiz.model;

// Generated Dec 24, 2012 12:09:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Robbusiness generated by hbm2java
 */
@Entity
@Table(name = "robbusiness")
public class RobBusiness implements java.io.Serializable {

	private String vchregistrationnumber;
	private long srlbusinesskeycode;
	private String chrcheckdigit;
	private String vchreferencenumber;
	private String vchname;
	private String chrnametype;
	private Date dtstartbusinessdate;
	private Date dtendbusinessdate;
	private String chragreement;
	private Date dtagreementdate;
	private Date dtregistrationdate;
	private String vchdescription;
	private String chrstatus;
	private String chrresponsibilitycode;
	private String chrbrstatus;
	private String chrbrpartstatus;
	private String chrbrblacklistedind;
	private String chrbrflag;
	private Short intbrownercount;
	private Date dtterminationdate;
	private String chrbrtermcause;
	private Date dtamendmentdate;
	private String vchmainaddress;
	private String vchmaintown;
	private String vchmainpostcode;
	private String vchmainstate;
	private String chrpostaddressflag;
	private String vchpostaddress;
	private String vchposttown;
	private String vchpostpostcode;
	private String vchpoststate;
	private String vchcreateby;
	private Date dtcreatedate;
	private String vchupdateby;
	private Date dtupdatedate;
	private Short insId;
	private String chrname;
	private Short intbranchcount;
	private String vchphone;
	private String vchemail;
	private String vchmobile;
	private String vchpostemail;
	private String vchpostphone;
	private String vchpostmobile;
	private String vchmainaddress1;
	private String vchmainaddress2;
	private String vchpostaddress1;
	private String vchpostaddress2;
//	private String categorytype;

	public RobBusiness() {
	}

	public RobBusiness(String vchregistrationnumber, long srlbusinesskeycode, String vchcreateby, Date dtcreatedate, String vchupdateby,
			Date dtupdatedate) {
		this.vchregistrationnumber = vchregistrationnumber;
		this.srlbusinesskeycode = srlbusinesskeycode;
		this.vchcreateby = vchcreateby;
		this.dtcreatedate = dtcreatedate;
		this.vchupdateby = vchupdateby;
		this.dtupdatedate = dtupdatedate;
	}

	public RobBusiness(String vchregistrationnumber, long srlbusinesskeycode, String chrcheckdigit, String vchreferencenumber, String vchname,
			String chrnametype, Date dtstartbusinessdate, Date dtendbusinessdate, String chragreement, Date dtagreementdate, Date dtregistrationdate,
			String vchdescription, String chrstatus, String chrresponsibilitycode, String chrbrstatus, String chrbrpartstatus,
			String chrbrblacklistedind, String chrbrflag, Short intbrownercount, Date dtterminationdate, String chrbrtermcause, Date dtamendmentdate,
			String vchmainaddress, String vchmaintown, String vchmainpostcode, String vchmainstate, String chrpostaddressflag, String vchpostaddress,
			String vchposttown, String vchpostpostcode, String vchpoststate, String vchcreateby, Date dtcreatedate, String vchupdateby,
			Date dtupdatedate, Short insId, String chrname, Short intbranchcount, String vchphone, String vchemail, String vchmobile,
			String vchpostemail, String vchpostphone, String vchpostmobile, String vchmainaddress1, String vchmainaddress2, String vchpostaddress1,
			String vchpostaddress2) {
		this.vchregistrationnumber = vchregistrationnumber;
		this.srlbusinesskeycode = srlbusinesskeycode;
		this.chrcheckdigit = chrcheckdigit;
		this.vchreferencenumber = vchreferencenumber;
		this.vchname = vchname;
		this.chrnametype = chrnametype;
		this.dtstartbusinessdate = dtstartbusinessdate;
		this.dtendbusinessdate = dtendbusinessdate;
		this.chragreement = chragreement;
		this.dtagreementdate = dtagreementdate;
		this.dtregistrationdate = dtregistrationdate;
		this.vchdescription = vchdescription;
		this.chrstatus = chrstatus;
		this.chrresponsibilitycode = chrresponsibilitycode;
		this.chrbrstatus = chrbrstatus;
		this.chrbrpartstatus = chrbrpartstatus;
		this.chrbrblacklistedind = chrbrblacklistedind;
		this.chrbrflag = chrbrflag;
		this.intbrownercount = intbrownercount;
		this.dtterminationdate = dtterminationdate;
		this.chrbrtermcause = chrbrtermcause;
		this.dtamendmentdate = dtamendmentdate;
		this.vchmainaddress = vchmainaddress;
		this.vchmaintown = vchmaintown;
		this.vchmainpostcode = vchmainpostcode;
		this.vchmainstate = vchmainstate;
		this.chrpostaddressflag = chrpostaddressflag;
		this.vchpostaddress = vchpostaddress;
		this.vchposttown = vchposttown;
		this.vchpostpostcode = vchpostpostcode;
		this.vchpoststate = vchpoststate;
		this.vchcreateby = vchcreateby;
		this.dtcreatedate = dtcreatedate;
		this.vchupdateby = vchupdateby;
		this.dtupdatedate = dtupdatedate;
		this.insId = insId;
		this.chrname = chrname;
		this.intbranchcount = intbranchcount;
		this.vchphone = vchphone;
		this.vchemail = vchemail;
		this.vchmobile = vchmobile;
		this.vchpostemail = vchpostemail;
		this.vchpostphone = vchpostphone;
		this.vchpostmobile = vchpostmobile;
		this.vchmainaddress1 = vchmainaddress1;
		this.vchmainaddress2 = vchmainaddress2;
		this.vchpostaddress1 = vchpostaddress1;
		this.vchpostaddress2 = vchpostaddress2;
//		this.categorytype = categorytype;
	}

	@Id
	@Column(name = "vchregistrationnumber", unique = true, length = 9)
	public String getVchregistrationnumber() {
		return this.vchregistrationnumber;
	}

	public void setVchregistrationnumber(String vchregistrationnumber) {
		this.vchregistrationnumber = vchregistrationnumber;
	}

	@Column(name = "srlbusinesskeycode", nullable = false, insertable = false, updatable = false)
	public long getSrlbusinesskeycode() {
		return this.srlbusinesskeycode;
	}

	public void setSrlbusinesskeycode(long srlbusinesskeycode) {
		this.srlbusinesskeycode = srlbusinesskeycode;
	}

	@Column(name = "chrcheckdigit", length = 1)
	public String getChrcheckdigit() {
		return this.chrcheckdigit;
	}

	public void setChrcheckdigit(String chrcheckdigit) {
		this.chrcheckdigit = chrcheckdigit;
	}

	@Column(name = "vchreferencenumber", unique = true, length = 25)
	public String getVchreferencenumber() {
		return this.vchreferencenumber;
	}

	public void setVchreferencenumber(String vchreferencenumber) {
		this.vchreferencenumber = vchreferencenumber;
	}

	@Column(name = "vchname", length = 70)
	public String getVchname() {
		return this.vchname;
	}

	public void setVchname(String vchname) {
		this.vchname = vchname;
	}

	@Column(name = "chrnametype", length = 1)
	public String getChrnametype() {
		return this.chrnametype;
	}

	public void setChrnametype(String chrnametype) {
		this.chrnametype = chrnametype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtstartbusinessdate", length = 2052)
	public Date getDtstartbusinessdate() {
		return this.dtstartbusinessdate;
	}

	public void setDtstartbusinessdate(Date dtstartbusinessdate) {
		this.dtstartbusinessdate = dtstartbusinessdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtendbusinessdate", length = 2052)
	public Date getDtendbusinessdate() {
		return this.dtendbusinessdate;
	}

	public void setDtendbusinessdate(Date dtendbusinessdate) {
		this.dtendbusinessdate = dtendbusinessdate;
	}

	@Column(name = "chragreement", length = 1)
	public String getChragreement() {
		return this.chragreement;
	}

	public void setChragreement(String chragreement) {
		this.chragreement = chragreement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtagreementdate", length = 2052)
	public Date getDtagreementdate() {
		return this.dtagreementdate;
	}

	public void setDtagreementdate(Date dtagreementdate) {
		this.dtagreementdate = dtagreementdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtregistrationdate", length = 2052)
	public Date getDtregistrationdate() {
		return this.dtregistrationdate;
	}

	public void setDtregistrationdate(Date dtregistrationdate) {
		this.dtregistrationdate = dtregistrationdate;
	}

	@Column(name = "vchdescription", length = 1500)
	public String getVchdescription() {
		return this.vchdescription;
	}

	public void setVchdescription(String vchdescription) {
		this.vchdescription = vchdescription;
	}

	@Column(name = "chrstatus", length = 1)
	public String getChrstatus() {
		return this.chrstatus;
	}

	public void setChrstatus(String chrstatus) {
		this.chrstatus = chrstatus;
	}

	@Column(name = "chrresponsibilitycode", length = 1)
	public String getChrresponsibilitycode() {
		return this.chrresponsibilitycode;
	}

	public void setChrresponsibilitycode(String chrresponsibilitycode) {
		this.chrresponsibilitycode = chrresponsibilitycode;
	}

	@Column(name = "chrbrstatus", length = 1)
	public String getChrbrstatus() {
		return this.chrbrstatus;
	}

	public void setChrbrstatus(String chrbrstatus) {
		this.chrbrstatus = chrbrstatus;
	}

	@Column(name = "chrbrpartstatus", length = 1)
	public String getChrbrpartstatus() {
		return this.chrbrpartstatus;
	}

	public void setChrbrpartstatus(String chrbrpartstatus) {
		this.chrbrpartstatus = chrbrpartstatus;
	}

	@Column(name = "chrbrblacklistedind", length = 1)
	public String getChrbrblacklistedind() {
		return this.chrbrblacklistedind;
	}

	public void setChrbrblacklistedind(String chrbrblacklistedind) {
		this.chrbrblacklistedind = chrbrblacklistedind;
	}

	@Column(name = "chrbrflag", length = 1)
	public String getChrbrflag() {
		return this.chrbrflag;
	}

	public void setChrbrflag(String chrbrflag) {
		this.chrbrflag = chrbrflag;
	}

	@Column(name = "intbrownercount")
	public Short getIntbrownercount() {
		return this.intbrownercount;
	}

	public void setIntbrownercount(Short intbrownercount) {
		this.intbrownercount = intbrownercount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtterminationdate", length = 2052)
	public Date getDtterminationdate() {
		return this.dtterminationdate;
	}

	public void setDtterminationdate(Date dtterminationdate) {
		this.dtterminationdate = dtterminationdate;
	}

	@Column(name = "chrbrtermcause", length = 1)
	public String getChrbrtermcause() {
		return this.chrbrtermcause;
	}

	public void setChrbrtermcause(String chrbrtermcause) {
		this.chrbrtermcause = chrbrtermcause;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtamendmentdate", length = 2052)
	public Date getDtamendmentdate() {
		return this.dtamendmentdate;
	}

	public void setDtamendmentdate(Date dtamendmentdate) {
		this.dtamendmentdate = dtamendmentdate;
	}

	@Column(name = "vchmainaddress", length = 70)
	public String getVchmainaddress() {
		return this.vchmainaddress;
	}

	public void setVchmainaddress(String vchmainaddress) {
		this.vchmainaddress = vchmainaddress;
	}

	@Column(name = "vchmaintown", length = 20)
	public String getVchmaintown() {
		return this.vchmaintown;
	}

	public void setVchmaintown(String vchmaintown) {
		this.vchmaintown = vchmaintown;
	}

	@Column(name = "vchmainpostcode", length = 5)
	public String getVchmainpostcode() {
		return this.vchmainpostcode;
	}

	public void setVchmainpostcode(String vchmainpostcode) {
		this.vchmainpostcode = vchmainpostcode;
	}

	@Column(name = "vchmainstate", length = 1)
	public String getVchmainstate() {
		return this.vchmainstate;
	}

	public void setVchmainstate(String vchmainstate) {
		this.vchmainstate = vchmainstate;
	}

	@Column(name = "chrpostaddressflag", length = 1)
	public String getChrpostaddressflag() {
		return this.chrpostaddressflag;
	}

	public void setChrpostaddressflag(String chrpostaddressflag) {
		this.chrpostaddressflag = chrpostaddressflag;
	}

	@Column(name = "vchpostaddress", length = 70)
	public String getVchpostaddress() {
		return this.vchpostaddress;
	}

	public void setVchpostaddress(String vchpostaddress) {
		this.vchpostaddress = vchpostaddress;
	}

	@Column(name = "vchposttown", length = 20)
	public String getVchposttown() {
		return this.vchposttown;
	}

	public void setVchposttown(String vchposttown) {
		this.vchposttown = vchposttown;
	}

	@Column(name = "vchpostpostcode", length = 5)
	public String getVchpostpostcode() {
		return this.vchpostpostcode;
	}

	public void setVchpostpostcode(String vchpostpostcode) {
		this.vchpostpostcode = vchpostpostcode;
	}

	@Column(name = "vchpoststate", length = 1)
	public String getVchpoststate() {
		return this.vchpoststate;
	}

	public void setVchpoststate(String vchpoststate) {
		this.vchpoststate = vchpoststate;
	}

	@Column(name = "vchcreateby", nullable = false, length = 10)
	public String getVchcreateby() {
		return this.vchcreateby;
	}

	public void setVchcreateby(String vchcreateby) {
		this.vchcreateby = vchcreateby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtcreatedate", nullable = false, length = 3594)
	public Date getDtcreatedate() {
		return this.dtcreatedate;
	}

	public void setDtcreatedate(Date dtcreatedate) {
		this.dtcreatedate = dtcreatedate;
	}

	@Column(name = "vchupdateby", nullable = false, length = 10)
	public String getVchupdateby() {
		return this.vchupdateby;
	}

	public void setVchupdateby(String vchupdateby) {
		this.vchupdateby = vchupdateby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dtupdatedate", nullable = false, length = 3594)
	public Date getDtupdatedate() {
		return this.dtupdatedate;
	}

	public void setDtupdatedate(Date dtupdatedate) {
		this.dtupdatedate = dtupdatedate;
	}

	@Column(name = "ins_id")
	public Short getInsId() {
		return this.insId;
	}

	public void setInsId(Short insId) {
		this.insId = insId;
	}

	@Column(name = "chrname", length = 1)
	public String getChrname() {
		return this.chrname;
	}

	public void setChrname(String chrname) {
		this.chrname = chrname;
	}

	@Column(name = "intbranchcount")
	public Short getIntbranchcount() {
		return this.intbranchcount;
	}

	public void setIntbranchcount(Short intbranchcount) {
		this.intbranchcount = intbranchcount;
	}

	@Column(name = "vchphone", length = 11)
	public String getVchphone() {
		return this.vchphone;
	}

	public void setVchphone(String vchphone) {
		this.vchphone = vchphone;
	}

	@Column(name = "vchemail", length = 30)
	public String getVchemail() {
		return this.vchemail;
	}

	public void setVchemail(String vchemail) {
		this.vchemail = vchemail;
	}

	@Column(name = "vchmobile", length = 11)
	public String getVchmobile() {
		return this.vchmobile;
	}

	public void setVchmobile(String vchmobile) {
		this.vchmobile = vchmobile;
	}

	@Column(name = "vchpostemail", length = 30)
	public String getVchpostemail() {
		return this.vchpostemail;
	}

	public void setVchpostemail(String vchpostemail) {
		this.vchpostemail = vchpostemail;
	}

	@Column(name = "vchpostphone", length = 11)
	public String getVchpostphone() {
		return this.vchpostphone;
	}

	public void setVchpostphone(String vchpostphone) {
		this.vchpostphone = vchpostphone;
	}

	@Column(name = "vchpostmobile", length = 11)
	public String getVchpostmobile() {
		return this.vchpostmobile;
	}

	public void setVchpostmobile(String vchpostmobile) {
		this.vchpostmobile = vchpostmobile;
	}

	@Column(name = "vchmainaddress1", length = 70)
	public String getVchmainaddress1() {
		return this.vchmainaddress1;
	}

	public void setVchmainaddress1(String vchmainaddress1) {
		this.vchmainaddress1 = vchmainaddress1;
	}

	@Column(name = "vchmainaddress2", length = 70)
	public String getVchmainaddress2() {
		return this.vchmainaddress2;
	}

	public void setVchmainaddress2(String vchmainaddress2) {
		this.vchmainaddress2 = vchmainaddress2;
	}

	@Column(name = "vchpostaddress1", length = 70)
	public String getVchpostaddress1() {
		return this.vchpostaddress1;
	}

	public void setVchpostaddress1(String vchpostaddress1) {
		this.vchpostaddress1 = vchpostaddress1;
	}

	@Column(name = "vchpostaddress2", length = 70)
	public String getVchpostaddress2() {
		return this.vchpostaddress2;
	}

	public void setVchpostaddress2(String vchpostaddress2) {
		this.vchpostaddress2 = vchpostaddress2;
	}

//	@Column(name = "categorytype", length = 2)
//	public String getCategorytype() {
//		return this.categorytype;
//	}
//
//	public void setCategorytype(String categorytype) {
//		this.categorytype = categorytype;
//	}

}
